# Generated by AI (UnitTest MCP)
"""Manager action tools — bounded integrate-beat moves exposed as dream tools."""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from chorus.heartbeat import BeatContext
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Goal,
    Ledger,
    ManagementProfile,
    Run,
    RunStatus,
    Task,
    TaskStatus,
)
from chorus.lifecycle import CapabilityService, MissionTeamPolicy
from chorus.lifecycle._capability import AssignTaskResult, SubmitTaskResult
from chorus.outcomes import OutcomeKind
from chorus.testing import uid
from chorus.workforce import Employee
from chorus_tools import AssignTaskTool, SubmitTaskTool

pytestmark = pytest.mark.integration

REV = uid("run_mgr_integrate_1")


def _ctx(working_dir: Path) -> object:
    from dream.tools._context import ToolExecutionContext

    return ToolExecutionContext(
        working_dir=working_dir,
        session_id="sess",
        metadata={},
        scratch_dir=working_dir,
        cancel_requested=False,
    )


def _seed(
    ledger: Ledger, *, allowed_professions: tuple[str, ...] = ("engineer",)
) -> None:
    lead = ledger.employees.create(Employee(id="mgr", name="Mgr", role="engineer"))
    ledger.employees.create(Employee(id="ada", name="Ada", role="engineer", reports_to="mgr"))
    ledger.employees.create(Employee(id="bob", name="Bob", role="engineer", reports_to="mgr"))
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="mgr",
            active=True,
            can_lead=True,
            can_subdelegate=True,
            max_delegation_depth=3,
            max_team_size=3,
            allowed_professions=allowed_professions,
            granted_by_user_id="operator",
        )
    )
    ledger.goals.create(Goal(id=uid("goal-M"), title="Ship it"))
    team_policy = MissionTeamPolicy(ledger)
    team = team_policy.create_for_root(lead, uid("goal-M"))
    team_policy.activate(team.id)
    ledger.tasks.submit(
        Task(
            id=uid("M"),
            intent="ship it",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id=team.id,
            assignee_employee_id="mgr",
            goal_id=uid("goal-M"),
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("M"),
            team_id=team.id,
            lead_employee_id="mgr",
            management_profile_version=1,
            can_subdelegate=True,
            max_depth=3,
            max_team_size=3,
            objective_rubric="Ship it",
            status=DelegationContractStatus.INTEGRATING,
        )
    )
    ledger.runs.create(Run(id=REV, employee_id="mgr", task_id=uid("M"), status=RunStatus.RUNNING))


def test_submit_task_tool_creates_one_child(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)

    result = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {"label": "fix", "intent": "fix the integration gap", "assignee": "ada", "files_to_touch": ["src/fix.py"]},
            _ctx(tmp_path),
        )
    )

    assert result.is_error is False
    child_id = result.structured["child_id"]
    child = ledger.tasks.get(child_id)
    assert child is not None
    assert child.parent_id == uid("M")
    assert child.assignee_employee_id == "ada"
    assert ledger.dependencies.unresolved_blockers(uid("M")) == [child_id]


def test_submit_task_tool_rejects_non_report(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    ledger.employees.create(Employee(id="eve", name="Eve", role="engineer"))
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)

    result = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {"label": "fix", "intent": "fix", "assignee": "eve", "files_to_touch": ["src/fix.py"]},
            _ctx(tmp_path),
        )
    )

    assert result.is_error is True
    assert result.structured["unknown_assignees"] == ["eve"]
    assert ledger.dependencies.unresolved_blockers(uid("M")) == []


def test_assign_task_tool_routes_existing_child(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    submit = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {"label": "fix", "intent": "fix", "assignee": "ada", "files_to_touch": ["src/fix.py"]},
            _ctx(tmp_path),
        )
    )

    result = asyncio.run(
        AssignTaskTool(ledger).execute(
            {"task_id": submit.structured["child_id"], "assignee": "bob"},
            _ctx(tmp_path),
        )
    )

    assert result.is_error is False
    assert ledger.tasks.get(submit.structured["child_id"]).assignee_employee_id == "bob"  # type: ignore[union-attr]


def test_assign_task_tool_rejects_non_child(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    ledger.tasks.submit(
        Task(
            id=uid("outside"),
            intent=uid("outside"),
            status=TaskStatus.TODO,
            assignee_employee_id="ada",
        )
    )
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)

    result = asyncio.run(
        AssignTaskTool(ledger).execute(
            {"task_id": uid("outside"), "assignee": "bob"}, _ctx(tmp_path)
        )
    )

    assert result.is_error is True
    assert result.structured["not_child"] is True


def test_submit_task_tool_rejects_empty_files_to_touch(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)

    result = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {"label": "fix", "intent": "fix", "assignee": "ada", "files_to_touch": []},
            _ctx(tmp_path),
        )
    )

    assert result.is_error is True


def test_submit_tool_forwards_actor_and_execution_mode(
    ledger: Ledger, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    captured: dict[str, object] = {}

    def fake_submit(self: CapabilityService, **kwargs: object) -> SubmitTaskResult:
        captured.update(kwargs)
        return SubmitTaskResult(child_id=uid("task-area"))

    monkeypatch.setattr(CapabilityService, "submit_one", fake_submit)
    result = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {
                "label": "area",
                "intent": "lead an area",
                "assignee": "ada",
                "execution_mode": "delegation",
                "files_to_touch": ["src/area.py"],
            },
            _ctx(tmp_path),
        )
    )

    child = captured["child"]
    assert captured["actor_employee_id"] == "mgr"
    assert child.execution_mode is ExecutionMode.DELEGATION  # type: ignore[union-attr]
    assert child.files_to_touch == ("src/area.py",)  # type: ignore[union-attr]
    assert child.outcome_kind is None  # type: ignore[union-attr]
    assert result.is_error is False


def test_submit_tool_omitted_outcome_kind_skips_capability_check(
    ledger: Ledger, tmp_path: Path
) -> None:
    """Omitting outcome_kind is backward-safe: a pm may receive undeclared work."""
    _seed(ledger, allowed_professions=("engineer", "pm"))
    ledger.employees.create(Employee(id="pam", name="Pam", role="pm", reports_to="mgr"))
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    result = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {"label": "spec", "intent": "write the api spec", "assignee": "pam", "files_to_touch": ["docs/spec.md"]},
            _ctx(tmp_path),
        )
    )
    assert result.is_error is False
    child = ledger.tasks.get(result.structured["child_id"])
    assert child is not None
    assert child.assignee_employee_id == "pam"


def test_submit_tool_refuses_declared_pr_child_assigned_to_a_pm(
    ledger: Ledger, tmp_path: Path
) -> None:
    _seed(ledger, allowed_professions=("engineer", "pm"))
    ledger.employees.create(Employee(id="pam", name="Pam", role="pm", reports_to="mgr"))
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    result = asyncio.run(
        SubmitTaskTool(ledger).execute(
            {
                "label": "impl",
                "intent": "build it",
                "assignee": "pam",
                "outcome_kind": OutcomeKind.PR.value,
                "files_to_touch": ["src/impl.py"],
            },
            _ctx(tmp_path),
        )
    )
    assert result.is_error is True
    assert "pam" in result.content
    mismatches = result.structured["outcome_mismatches"]
    assert mismatches[0]["declared"] == OutcomeKind.PR.value
    assert mismatches[0]["role_kind"] == OutcomeKind.DOC.value
    assert ledger.dependencies.unresolved_blockers(uid("M")) == []


def test_assign_tool_surfaces_authority_denial(
    ledger: Ledger, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)

    def fake_reassign(self: CapabilityService, **kwargs: object) -> AssignTaskResult:
        assert kwargs["assigned_by"] == "mgr"
        return AssignTaskResult(authority_denied="management profile version is stale")

    monkeypatch.setattr(CapabilityService, "reassign", fake_reassign)
    result = asyncio.run(
        AssignTaskTool(ledger).execute(
            {"task_id": uid("child"), "assignee": "ada"},
            _ctx(tmp_path),
        )
    )

    assert result.is_error is True
    assert result.structured["authority_denied"] == "management profile version is stale"
