# Generated by AI (UnitTest MCP)
"""DecomposeTool — the chorus ``decompose`` capability as a model-callable dream tool (M3 Slice 1).

The tool is the dream envelope around :class:`~chorus.lifecycle.CapabilityService`: it validates the
model's children DAG, reads the per-beat :class:`~chorus.heartbeat.BeatContext` from ``ctx.working_dir``
to learn its parent task + run, and fans the task out. These tests drive ``execute`` directly (no model
in the loop) with a written beat-context file standing in for the kernel.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from chorus.heartbeat import BeatContext
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Goal,
    Ledger,
    ManagementProfile,
    Run,
    RunStatus,
    Task,
    TaskStatus,
)
from chorus.lifecycle import CapabilityService, DecomposeResult, MissionTeamPolicy
from chorus.testing import uid
from chorus.workforce import Employee
from chorus_tools import DecomposeTool

pytestmark = pytest.mark.integration

REV = uid("run_mgr_1")


def _ctx(working_dir: Path) -> object:
    from dream.tools._context import ToolExecutionContext

    return ToolExecutionContext(
        working_dir=working_dir,
        session_id="sess",
        metadata={},
        scratch_dir=working_dir,
        cancel_requested=False,
    )


def _seed(ledger: Ledger) -> None:
    lead = ledger.employees.create(Employee(id="mgr", name="Mgr", role="engineer"))
    ledger.employees.create(Employee(id="ada", name="Ada", role="engineer", reports_to="mgr"))
    ledger.employees.create(Employee(id="bob", name="Bob", role="engineer", reports_to="mgr"))
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="mgr",
            active=True,
            can_lead=True,
            can_subdelegate=True,
            max_delegation_depth=3,
            max_team_size=3,
            allowed_professions=("engineer",),
            granted_by_user_id="operator",
        )
    )
    ledger.goals.create(Goal(id=uid("goal-M"), title="Ship it"))
    team_policy = MissionTeamPolicy(ledger)
    team = team_policy.create_for_root(lead, uid("goal-M"))
    team_policy.activate(team.id)
    ledger.tasks.submit(
        Task(
            id=uid("M"),
            intent="ship it",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id=team.id,
            assignee_employee_id="mgr",
            goal_id=uid("goal-M"),
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("M"),
            team_id=team.id,
            lead_employee_id="mgr",
            management_profile_version=1,
            can_subdelegate=True,
            max_depth=3,
            max_team_size=3,
            objective_rubric="Ship it",
            status=DelegationContractStatus.DELEGATED,
        )
    )
    ledger.runs.create(Run(id=REV, employee_id="mgr", task_id=uid("M"), status=RunStatus.RUNNING))


def test_tool_fans_out_and_assigns(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    tool = DecomposeTool(ledger)

    result = asyncio.run(
        tool.execute(
            {
                "children": [
                    {
                        "label": "api",
                        "intent": "build the api",
                        "assignee": "ada",
                        "files_to_touch": ["src/api.py"],
                    },
                    {
                        "label": "tests",
                        "intent": "write tests",
                        "assignee": "bob",
                        "depends_on": ["api"],
                        "files_to_touch": ["tests/test_api.py"],
                    },
                ]
            },
            _ctx(tmp_path),
        )
    )

    assert result.is_error is False
    child_ids = result.structured["children"]
    assert set(child_ids) == {"api", "tests"}
    # children are real, assigned, and the parent waits on its subtree
    assert ledger.tasks.get(child_ids["api"]).assignee_employee_id == "ada"  # type: ignore[union-attr]
    assert set(ledger.dependencies.unresolved_blockers(uid("M"))) == set(child_ids.values())
    # the sibling edge is wired
    assert ledger.dependencies.unresolved_blockers(child_ids["tests"]) == [child_ids["api"]]


def test_tool_declares_a_repo_write_trust_tier(ledger: Ledger) -> None:
    # A mutating tool is gated as a write effect; its declared tier must be REPO_WRITE (1) so dream
    # trusts it at the manager's session tier instead of denying it ("not trusted for write").
    assert DecomposeTool(ledger).declaration.tier_required == 1


def test_tool_rejects_empty_children(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    result = asyncio.run(DecomposeTool(ledger).execute({"children": []}, _ctx(tmp_path)))
    assert result.is_error is True


def test_tool_rejects_malformed_input_as_recovery_not_crash(ledger: Ledger, tmp_path: Path) -> None:
    # A payload that fails schema validation must come back as the tool's recovery contract
    # (is_error result), never an unchained pydantic ValidationError that escapes the tool.
    _seed(ledger)
    result = asyncio.run(DecomposeTool(ledger).execute({}, _ctx(tmp_path)))  # missing 'children'
    assert result.is_error is True


def test_tool_rejects_unknown_dependency_label(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    result = asyncio.run(
        DecomposeTool(ledger).execute(
            {
                "children": [
                    {
                        "label": "api",
                        "intent": "x",
                        "assignee": "ada",
                        "depends_on": ["ghost"],
                        "files_to_touch": ["src/api.py"],
                    }
                ]
            },
            _ctx(tmp_path),
        )
    )
    assert result.is_error is True
    assert ledger.tasks.get(uid("M")) is not None  # nothing fanned out


def test_tool_rejects_empty_files_to_touch(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)

    result = asyncio.run(
        DecomposeTool(ledger).execute(
            {
                "children": [
                    {
                        "label": "api",
                        "intent": "x",
                        "assignee": "ada",
                        "files_to_touch": [],
                    }
                ]
            },
            _ctx(tmp_path),
        )
    )

    assert result.is_error is True


def test_tool_is_idempotent_on_refire(ledger: Ledger, tmp_path: Path) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    tool = DecomposeTool(ledger)
    payload = {
        "children": [
            {
                "label": "api",
                "intent": "build the api",
                "assignee": "ada",
                "files_to_touch": ["src/api.py"],
            }
        ]
    }
    first = asyncio.run(tool.execute(payload, _ctx(tmp_path)))
    second = asyncio.run(tool.execute(payload, _ctx(tmp_path)))  # the generator re-fired
    assert first.structured["children"] == second.structured["children"]
    assert len(ledger.dependencies.unresolved_blockers(uid("M"))) == 1  # no duplicate child


def test_tool_forwards_actor_and_explicit_child_execution_mode(
    ledger: Ledger, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _seed(ledger)
    BeatContext(task_id=uid("M"), run_id=REV, employee_id="mgr").write(tmp_path)
    captured: dict[str, object] = {}

    def fake_decompose(self: CapabilityService, **kwargs: object) -> DecomposeResult:
        captured.update(kwargs)
        return DecomposeResult(child_ids={"area": "task-area"})

    monkeypatch.setattr(CapabilityService, "decompose", fake_decompose)
    result = asyncio.run(
        DecomposeTool(ledger).execute(
            {
                "children": [
                    {
                        "label": "area",
                        "intent": "lead an area",
                        "assignee": "ada",
                        "execution_mode": "delegation",
                        "files_to_touch": ["src/area.py"],
                    }
                ]
            },
            _ctx(tmp_path),
        )
    )

    children = captured["children"]
    assert captured["actor_employee_id"] == "mgr"
    assert children[0].execution_mode is ExecutionMode.DELEGATION  # type: ignore[index]
    assert children[0].files_to_touch == ("src/area.py",)  # type: ignore[index]
    assert result.is_error is False
