# Generated by AI (UnitTest MCP)
"""Read-only roster context scoped to the current delegation contract."""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from chorus.heartbeat import BeatContext
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    ManagementProfile,
    SqliteLedger,
    Task,
    TaskStatus,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.workforce import Employee, EmployeeStatus
from chorus_tools import TeamReadTool

pytestmark = pytest.mark.integration


def _ctx(working_dir: Path) -> object:
    from dream.tools._context import ToolExecutionContext

    return ToolExecutionContext(
        working_dir=working_dir,
        session_id="sess",
        metadata={},
        scratch_dir=working_dir,
        cancel_requested=False,
    )


def _seed_delegation(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="architect"))
    ledger.employees.create(Employee(id="ada", name="Ada", role="engineer", reports_to="lead"))
    ledger.employees.create(Employee(id="bob", name="Bob", role="designer", reports_to="lead"))
    ledger.employees.create(
        Employee(
            id="pat",
            name="Pat",
            role="engineer",
            reports_to="lead",
            status=EmployeeStatus.PAUSED,
        )
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="lead",
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            can_subdelegate=True,
            max_delegation_depth=4,
            max_team_size=5,
            allowed_professions=("engineer",),
            spend_limit_cents=50_000,
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id="team-1",
            name="Mission: Ship",
            lead_employee_id="lead",
            created_by="lead",
            status=TeamStatus.ACTIVE,
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id="team-1",
            employee_id="lead",
            source_manager_id="lead",
            membership_role=TeamMembershipRole.LEAD,
            can_subdelegate=True,
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id="team-1",
            employee_id="ada",
            source_manager_id="lead",
        )
    )
    ledger.tasks.submit(
        Task(
            id="root",
            intent="Ship",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id="team-1",
            assignee_employee_id="lead",
        )
    )
    ledger.tasks.submit(
        Task(
            id="ada-existing",
            intent="Existing work",
            status=TaskStatus.IN_PROGRESS,
            assignee_employee_id="ada",
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id="root",
            team_id="team-1",
            lead_employee_id="lead",
            management_profile_version=1,
            objective_rubric="Ship",
            can_subdelegate=True,
            max_depth=3,
            max_team_size=3,
            spend_limit_cents=20_000,
            status=DelegationContractStatus.DELEGATED,
        )
    )


def test_team_read_returns_safe_contract_scoped_roster(
    ledger: SqliteLedger, tmp_path: Path
) -> None:
    _seed_delegation(ledger)
    BeatContext(task_id="root", run_id="run-1", employee_id="lead").write(tmp_path)

    result = asyncio.run(TeamReadTool(ledger).execute({}, _ctx(tmp_path)))

    assert result.is_error is False
    assert result.structured["team"] == {
        "id": "team-1",
        "name": "Mission: Ship",
        "status": "active",
        "lead_employee_id": "lead",
    }
    assert result.structured["contract"]["task_id"] == "root"
    assert [member["employee_id"] for member in result.structured["current_members"]] == [
        "lead",
        "ada",
    ]
    assert result.structured["legal_direct_reports"] == [
        {
            "employee_id": "ada",
            "profession": "engineer",
            "reports_to": "lead",
            "status": "idle",
            "observed_load": 1,
        }
    ]
    assert result.structured["team_candidates"] == []
    assert result.structured["observed_load"] == {"ada": 1, "lead": 1}
    assert result.structured["management_limits"] == {
        "management_profile_version": 1,
        "can_subdelegate": True,
        "max_depth": 3,
        "max_team_size": 3,
        "max_direct_children": None,
        "spend_limit_cents": 20_000,
        "allowed_professions": ["engineer"],
    }
    assert "lead: profession=architect, reports_to=none, membership_role=lead" in result.content
    assert "ada: profession=engineer, reports_to=lead, membership_role=member" in result.content
    assert "Use these exact employee_id values in decompose.assignee" in result.content


def test_team_read_lists_legal_unassigned_candidate(ledger: SqliteLedger, tmp_path: Path) -> None:
    _seed_delegation(ledger)
    ledger.team_members.remove("team-1", "ada")
    BeatContext(task_id="root", run_id="run-1", employee_id="lead").write(tmp_path)

    result = asyncio.run(TeamReadTool(ledger).execute({}, _ctx(tmp_path)))

    assert [candidate["employee_id"] for candidate in result.structured["team_candidates"]] == [
        "ada"
    ]
    assert "Legal candidates:" in result.content
    assert "ada: profession=engineer, reports_to=lead, status=idle" in result.content


def test_team_read_refuses_non_lead_actor(ledger: SqliteLedger, tmp_path: Path) -> None:
    _seed_delegation(ledger)
    BeatContext(task_id="root", run_id="run-1", employee_id="ada").write(tmp_path)

    result = asyncio.run(TeamReadTool(ledger).execute({}, _ctx(tmp_path)))

    assert result.is_error is True
    assert "not the delegation contract lead" in result.content


def test_team_read_refuses_non_delegation_beat(ledger: SqliteLedger, tmp_path: Path) -> None:
    ledger.employees.create(Employee(id="ada", name="Ada", role="engineer"))
    ledger.tasks.submit(
        Task(id="plain", intent="Plain", status=TaskStatus.TODO, assignee_employee_id="ada")
    )
    BeatContext(task_id="plain", run_id="run-1", employee_id="ada").write(tmp_path)

    result = asyncio.run(TeamReadTool(ledger).execute({}, _ctx(tmp_path)))

    assert result.is_error is True
    assert "active delegation contract" in result.content
