# Generated by AI (UnitTest MCP unavailable in this session)
"""CEO workforce catalog and typed proposal tools."""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

import pytest

from chorus.heartbeat import BeatContext
from chorus.ledger import SqliteLedger, WorkforcePlanStatus
from chorus.roles import RoleRegistry, default_roles
from chorus.workforce import Employee, EmployeeStatus
from chorus_tools import WorkforceCatalogReadTool, WorkforcePlanProposeTool

pytestmark = pytest.mark.integration


def _ctx(working_dir: Path) -> object:
    from dream.tools._context import ToolExecutionContext

    return ToolExecutionContext(
        working_dir=working_dir,
        session_id="sess",
        metadata={},
        scratch_dir=working_dir,
        cancel_requested=False,
    )


def _roles() -> RoleRegistry:
    return RoleRegistry.from_plugins(default_roles())


def _payload() -> dict[str, object]:
    return {
        "rationale": "A shallow product group covers the approved goal.",
        "confidence": 0.8,
        "source_goal_ids": ["goal-1"],
        "employees": [
            {
                "ref": "product-lead",
                "name": "Product Lead",
                "profession": "pm",
                "reports_to_ref": "ceo",
                "responsibilities": ["Own product execution"],
            },
            {
                "ref": "analyst",
                "name": "Analyst",
                "profession": "analyst",
                "reports_to_ref": "product-lead",
                "responsibilities": ["Analyze feedback"],
            },
        ],
        "management_grants": [
            {
                "employee_ref": "ceo",
                "can_lead": True,
                "can_subdelegate": True,
                "max_delegation_depth": 2,
                "max_team_size": 2,
                "allowed_professions": ["pm"],
                "spend_limit_cents": 50_000,
            },
            {
                "employee_ref": "product-lead",
                "can_lead": True,
                "can_subdelegate": True,
                "max_delegation_depth": 1,
                "max_team_size": 2,
                "allowed_professions": ["analyst"],
                "spend_limit_cents": 20_000,
            },
        ],
    }


def test_catalog_exposes_analyst_and_excludes_legacy_professions(
    ledger: SqliteLedger, tmp_path: Path
) -> None:
    ledger.employees.create(
        Employee(id="ceo", name="CEO", role="ceo", status=EmployeeStatus.ACTIVE)
    )

    result = asyncio.run(WorkforceCatalogReadTool(ledger, _roles()).execute({}, _ctx(tmp_path)))

    assert result.is_error is False
    assert result.structured["hireable_professions"] == [
        "analyst",
        "backend_engineer",
        "designer",
        "frontend_engineer",
        "marketer",
        "pm",
    ]
    assert "engineer" not in result.structured["hireable_professions"]
    assert "manager" not in result.structured["hireable_professions"]
    assert "reviewer" not in result.structured["hireable_professions"]
    assert result.structured["proposal_contract"] == {
        "employees": "new hires only; omit current permanent employees",
        "existing_employee_references": ["ceo"],
        "existing_employee_reference_fields": [
            "employees[].reports_to_ref",
            "management_grants[].employee_ref",
        ],
    }
    assert "NEW HIRES ONLY" in result.content
    assert "use existing ids directly" in result.content


def test_ceo_tool_persists_proposal_without_hiring(ledger: SqliteLedger, tmp_path: Path) -> None:
    ledger.employees.create(
        Employee(id="ceo", name="CEO", role="ceo", status=EmployeeStatus.ACTIVE)
    )
    BeatContext(task_id="formation", run_id="run-1", employee_id="ceo").write(tmp_path)

    result = asyncio.run(
        WorkforcePlanProposeTool(ledger, _roles()).execute(_payload(), _ctx(tmp_path))
    )

    assert result.is_error is False
    plan = ledger.workforce_plans.latest(result.structured["plan_id"])
    assert plan is not None and plan.status is WorkforcePlanStatus.PROPOSED
    assert plan.proposed_by_employee_id == "ceo"
    assert [employee.id for employee in ledger.employees.list()] == ["ceo"]
    assert ledger.management_profiles.list() == []
    assert result.structured["evidence_path"] == "workforce_plan.json"
    evidence = json.loads((tmp_path / "workforce_plan.json").read_text(encoding="utf-8"))
    assert evidence["plan_id"] == plan.id
    assert evidence["status"] == "proposed"
    assert evidence["requires_human_approval"] is True
    assert [employee["ref"] for employee in evidence["employees"]] == [
        "product-lead",
        "analyst",
    ]
    assert [grant["employee_ref"] for grant in evidence["management_grants"]] == [
        "ceo",
        "product-lead",
    ]


def test_ceo_tool_returns_refusal_for_deep_plan_without_partial_writes(
    ledger: SqliteLedger, tmp_path: Path
) -> None:
    ledger.employees.create(
        Employee(id="ceo", name="CEO", role="ceo", status=EmployeeStatus.ACTIVE)
    )
    BeatContext(task_id="formation", run_id="run-1", employee_id="ceo").write(tmp_path)
    payload = _payload()
    payload["employees"] = [
        *payload["employees"],  # type: ignore[misc]
        {
            "ref": "too-deep",
            "name": "Too Deep",
            "profession": "designer",
            "reports_to_ref": "analyst",
        },
    ]

    result = asyncio.run(
        WorkforcePlanProposeTool(ledger, _roles()).execute(payload, _ctx(tmp_path))
    )

    assert result.is_error is True
    assert "depth" in result.content
    assert ledger.workforce_plans.list() == []
    assert [employee.id for employee in ledger.employees.list()] == ["ceo"]


def test_ceo_tool_refusal_explains_how_to_reference_existing_employees(
    ledger: SqliteLedger, tmp_path: Path
) -> None:
    ledger.employees.create(
        Employee(id="ceo", name="CEO", role="ceo", status=EmployeeStatus.ACTIVE)
    )
    BeatContext(task_id="formation", run_id="run-1", employee_id="ceo").write(tmp_path)
    payload = _payload()
    payload["employees"] = [
        {
            "ref": "new-ceo",
            "name": "CEO",
            "profession": "ceo",
            "reports_to_ref": "new-ceo",
        },
        *payload["employees"],  # type: ignore[misc]
    ]

    result = asyncio.run(
        WorkforcePlanProposeTool(ledger, _roles()).execute(payload, _ctx(tmp_path))
    )

    assert result.is_error is True
    assert "employees contains new hires only" in result.content
    assert "current employee ids directly" in result.content
    assert ledger.workforce_plans.list() == []
