# Generated by AI (UnitTest MCP)
"""CON-001: No sibling imports — architecture boundary enforcement.

Chorus production packages must not import horizon.
Horizon production package must not import chorus.
Dream owns shared contracts; explicit examples/tests composition roots are excluded.

Uses AST-based import detection covering ``import x`` and ``from x import y``.
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import NamedTuple

import pytest

# Paths
_REPO_ROOT = Path(__file__).resolve().parents[1]
_CHORUS_SRC = _REPO_ROOT / "src"
# Horizon lives in the main repo tree, not the worktree.
_HORIZON_SRC = _REPO_ROOT.parents[1] / "horizon" / "src"

# Chorus production package roots (CON-001 scope).
_CHORUS_PACKAGES = ("chorus", "chorus_harness", "chorus_tools", "chorus_employee", "chorus_cli")

# Horizon production package root.
_HORIZON_PACKAGE = "horizon"


class _Violation(NamedTuple):
    file: Path
    line: int
    statement: str


def _collect_python_files(root: Path) -> list[Path]:
    """Collect all .py files under *root*, excluding __pycache__."""
    return sorted(
        p
        for p in root.rglob("*.py")
        if "__pycache__" not in p.parts
    )


def _find_imports_of(source_file: Path, forbidden_roots: tuple[str, ...]) -> list[_Violation]:
    """Parse *source_file* with AST and return violations for forbidden imports."""
    tree = ast.parse(source_file.read_text(encoding="utf-8"), filename=str(source_file))

    violations: list[_Violation] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                if top in forbidden_roots:
                    violations.append(
                        _Violation(source_file, node.lineno, f"import {alias.name}")
                    )
        elif isinstance(node, ast.ImportFrom):
            if node.module is not None:
                top = node.module.split(".")[0]
                if top in forbidden_roots:
                    violations.append(
                        _Violation(source_file, node.lineno, f"from {node.module} import ...")
                    )
    return violations


# Chorus -> Horizon


def _chorus_production_files() -> list[Path]:
    """All .py files across all Chorus production packages."""
    files: list[Path] = []
    for pkg in _CHORUS_PACKAGES:
        pkg_dir = _CHORUS_SRC / pkg
        if pkg_dir.is_dir():
            files.extend(_collect_python_files(pkg_dir))
    return files


@pytest.mark.parametrize(
    "source_file",
    _chorus_production_files(),
    ids=lambda p: str(p.relative_to(_CHORUS_SRC)),
)
def test_chorus_does_not_import_horizon(source_file: Path) -> None:
    """CON-001: Chorus production code must not import horizon."""
    violations = _find_imports_of(source_file, (_HORIZON_PACKAGE,))
    assert not violations, (
        "CON-001 violation: Chorus file imports horizon.\n"
        + "\n".join(
            f"  {v.file.relative_to(_CHORUS_SRC)}:{v.line}  {v.statement}"
            for v in violations
        )
    )


# Horizon -> Chorus


def _horizon_production_files() -> list[Path]:
    """All .py files under the Horizon production package."""
    horizon_pkg = _HORIZON_SRC / _HORIZON_PACKAGE
    if not horizon_pkg.is_dir():
        pytest.skip(f"Horizon source not found at {horizon_pkg}")
    return _collect_python_files(horizon_pkg)


@pytest.mark.parametrize(
    "source_file",
    _horizon_production_files(),
    ids=lambda p: str(p.relative_to(_HORIZON_SRC)),
)
def test_horizon_does_not_import_chorus(source_file: Path) -> None:
    """CON-001: Horizon production code must not import chorus."""
    violations = _find_imports_of(source_file, _CHORUS_PACKAGES)
    assert not violations, (
        "CON-001 violation: Horizon file imports chorus.\n"
        + "\n".join(
            f"  {v.file.relative_to(_HORIZON_SRC)}:{v.line}  {v.statement}"
            for v in violations
        )
    )
