# Generated by AI (UnitTest MCP)
"""Task-aware execution profiles preserve craft delivery and seal delegation."""

from __future__ import annotations

from dataclasses import replace

import pytest

from chorus.heartbeat import ExecutionProfileDenied, ExecutionProfileResolver
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    ManagementProfile,
    SqliteLedger,
    Task,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.roles import RoleRegistry, default_roles, role_beat_config
from chorus.workforce import Employee

pytestmark = pytest.mark.unit


@pytest.fixture
def ledger() -> SqliteLedger:
    opened = SqliteLedger.open(":memory:")
    try:
        yield opened
    finally:
        opened.close()


def _seed_authorized_engineer(ledger: SqliteLedger) -> tuple[Employee, Task]:
    employee = Employee(id="lead", name="Lead", role="backend_engineer")
    ledger.employees.create(employee)
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="lead",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=3,
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    ledger.teams.create(
        Team(
            id="team-release",
            name="Release",
            lead_employee_id="lead",
            status=TeamStatus.ACTIVE,
            created_by="user-admin",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id="team-release",
            employee_id="lead",
            membership_role=TeamMembershipRole.LEAD,
            source_manager_id="lead",
        )
    )
    task = Task(
        id="task-release",
        intent="coordinate the release",
        execution_mode=ExecutionMode.DELEGATION,
        team_id="team-release",
        assignee_employee_id="lead",
    )
    ledger.tasks.submit(task)
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=task.id,
            team_id="team-release",
            lead_employee_id="lead",
            management_profile_version=1,
            max_depth=1,
            max_team_size=3,
            objective_rubric="all release outcomes are integrated and independently verified",
            status=DelegationContractStatus.DELEGATED,
        )
    )
    return employee, task


def test_delivery_mode_preserves_the_exact_profession_contract(ledger: SqliteLedger) -> None:
    roles = RoleRegistry.from_plugins(default_roles())
    employee = Employee(id="lead", name="Lead", role="backend_engineer")
    task = Task(
        id="task-delivery",
        intent="implement the API",
        assignee_employee_id="lead",
    )

    resolved = ExecutionProfileResolver(roles, ledger).resolve(employee, task)
    profession = roles.get("backend_engineer")

    assert resolved.config == role_beat_config(profession.manifest)
    assert resolved.verifier == profession.dod_generator(task.intent)
    assert resolved.outcome_kind == "pr"


@pytest.mark.parametrize(
    ("status", "expected_tools"),
    [
        (
            DelegationContractStatus.DELEGATED,
            ("read_file", "team_read", "staffing_request", "decompose"),
        ),
        (
            DelegationContractStatus.INTEGRATING,
            ("read_file", "team_read", "submit_task", "assign_task"),
        ),
        (DelegationContractStatus.VERIFYING, ("read_file", "team_read")),
    ],
)
def test_delegation_mode_returns_only_the_management_phase_contract(
    ledger: SqliteLedger,
    status: DelegationContractStatus,
    expected_tools: tuple[str, ...],
) -> None:
    employee, task = _seed_authorized_engineer(ledger)
    ledger.delegation_contracts.update_status(task.id, status)

    resolved = ExecutionProfileResolver(
        RoleRegistry.from_plugins(default_roles()), ledger
    ).resolve(employee, task)

    assert resolved.config.tools == expected_tools
    assert resolved.config.memory_scope == "team"
    assert "accountable lead" in resolved.config.system_prompt.lower()
    assert "engineering manager" not in resolved.config.system_prompt.lower()
    assert resolved.verifier.rubric() == (
        "all release outcomes are integrated and independently verified"
    )
    assert (resolved.verifier.artifact_class, resolved.outcome_kind) == ("subtree", "subtree")


def test_delegation_mode_rejects_a_stale_pinned_profile(ledger: SqliteLedger) -> None:
    employee, task = _seed_authorized_engineer(ledger)
    current = ledger.management_profiles.get(employee.id)
    assert current is not None
    ledger.management_profiles.upsert(replace(current, version=2, max_team_size=4))

    with pytest.raises(ExecutionProfileDenied, match="version"):
        ExecutionProfileResolver(RoleRegistry.from_plugins(default_roles()), ledger).resolve(
            employee, task
        )


def test_delegation_mode_rejects_an_employee_without_a_management_profile(
    ledger: SqliteLedger,
) -> None:
    employee = Employee(id="lead", name="Lead", role="backend_engineer")
    ledger.employees.create(employee)
    ledger.teams.create(
        Team(
            id="team-release",
            name="Release",
            lead_employee_id=employee.id,
            status=TeamStatus.ACTIVE,
            created_by="user-admin",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id="team-release",
            employee_id=employee.id,
            membership_role=TeamMembershipRole.LEAD,
            source_manager_id=employee.id,
        )
    )
    task = ledger.tasks.submit(
        Task(
            id="task-release",
            intent="coordinate the release",
            execution_mode=ExecutionMode.DELEGATION,
            team_id="team-release",
            assignee_employee_id=employee.id,
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=task.id,
            team_id="team-release",
            lead_employee_id=employee.id,
            management_profile_version=1,
            objective_rubric="integrate and verify the release",
            status=DelegationContractStatus.DELEGATED,
        )
    )

    with pytest.raises(ExecutionProfileDenied, match="management profile"):
        ExecutionProfileResolver(RoleRegistry.from_plugins(default_roles()), ledger).resolve(
            employee, task
        )