# Generated by AI (UnitTest MCP)
"""Task-aware authority selects the factory's complete harness surface."""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
from typing import Any

import pytest

from chorus.heartbeat import ExecutionProfileDenied
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    ManagementProfile,
    SqliteLedger,
    Task,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.roles import RoleRegistry, default_roles
from chorus.workforce import Employee
from chorus_harness import _factory as _factory_mod

pytestmark = pytest.mark.integration


@pytest.fixture
def ledger() -> SqliteLedger:
    opened = SqliteLedger.open(":memory:")
    try:
        yield opened
    finally:
        opened.close()


def _seed_tasks(ledger: SqliteLedger) -> tuple[Employee, Task, Task]:
    lead = Employee(id="lead", name="Lead", role="backend_engineer")
    worker = Employee(
        id="worker", name="Worker", role="backend_engineer", reports_to="lead"
    )
    ledger.employees.create(lead)
    ledger.employees.create(worker)
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=2,
            allowed_professions=("backend_engineer",),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id="team-release",
            name="Release",
            lead_employee_id=lead.id,
            created_by="user-admin",
            status=TeamStatus.ACTIVE,
        )
    )
    for employee_id, membership_role in (
        (lead.id, TeamMembershipRole.LEAD),
        (worker.id, TeamMembershipRole.MEMBER),
    ):
        ledger.team_members.add(
            TeamMember(
                team_id="team-release",
                employee_id=employee_id,
                source_manager_id=lead.id,
                membership_role=membership_role,
            )
        )

    delivery = Task(
        id="task-code",
        intent="implement the release endpoint",
        assignee_employee_id=lead.id,
    )
    delegation = Task(
        id="task-release",
        intent="coordinate the release",
        execution_mode=ExecutionMode.DELEGATION,
        team_id="team-release",
        assignee_employee_id=lead.id,
    )
    ledger.tasks.submit(delivery)
    ledger.tasks.submit(delegation)
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=delegation.id,
            team_id="team-release",
            lead_employee_id=lead.id,
            management_profile_version=1,
            max_depth=1,
            max_team_size=2,
            objective_rubric="integrate and verify the release subtree",
            status=DelegationContractStatus.DELEGATED,
        )
    )
    return lead, delivery, delegation


def _factory(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    ledger: SqliteLedger,
) -> tuple[_factory_mod.EmployeeHarnessFactory, list[dict[str, Any]]]:
    calls: list[dict[str, Any]] = []
    monkeypatch.setattr(
        _factory_mod.dream,
        "build_harness",
        lambda **kwargs: calls.append(kwargs) or object(),
    )
    return (
        _factory_mod.EmployeeHarnessFactory(
            api_key="k",
            base_url="https://x/openai/v1",
            deployment="gpt-x",
            company_id="acme",
            roles=RoleRegistry.from_plugins(default_roles()),
            work_root=tmp_path,
            ledger=ledger,
        ),
        calls,
    )


def test_same_backend_engineer_materializes_delivery_then_delegation_surface(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, ledger: SqliteLedger
) -> None:
    lead, delivery, delegation = _seed_tasks(ledger)
    factory, calls = _factory(monkeypatch, tmp_path, ledger)

    delivered = factory.materialize(lead, task_id=delivery.id)
    delegated = factory.materialize(lead, task_id=delegation.id)

    delivery_tools = {tool.name for tool in calls[0]["registry"].list_tools()}
    delegation_tools = {tool.name for tool in calls[1]["registry"].list_tools()}
    assert {"write_file", "bash", "git"} <= delivery_tools
    assert delegation_tools == {"read_file", "team_read", "staffing_request", "decompose"}
    assert delivered.config.memory_scope == "project"
    assert delegated.config.memory_scope == "team"
    assert "worker (backend_engineer)" in delegated.config.system_prompt


def test_stale_profile_is_denied_before_harness_build(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, ledger: SqliteLedger
) -> None:
    lead, _, delegation = _seed_tasks(ledger)
    profile = ledger.management_profiles.get(lead.id)
    assert profile is not None
    ledger.management_profiles.upsert(replace(profile, version=2))
    factory, calls = _factory(monkeypatch, tmp_path, ledger)

    with pytest.raises(ExecutionProfileDenied, match="version"):
        factory.materialize(lead, task_id=delegation.id)

    assert calls == []


def test_independent_verifier_uses_reviewer_read_only_surface_in_lead_worktree(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, ledger: SqliteLedger
) -> None:
    lead, _, delegation = _seed_tasks(ledger)
    reviewer = ledger.employees.create(Employee(id="reviewer", name="Reviewer", role="reviewer"))
    factory, calls = _factory(monkeypatch, tmp_path, ledger)

    factory.verification_runner_for(
        reviewer,
        task_id=delegation.id,
        worktree_owner_id=lead.id,
    )

    tools = {tool.name for tool in calls[0]["registry"].list_tools()}
    assert tools == {"read_file"}
    sandbox = Path(calls[0]["working_dir"]) / ".harness" / "sandbox.toml"
    assert 'tier = "read-only"' in sandbox.read_text(encoding="utf-8")