# Generated by AI (UnitTest MCP)
"""Active delegation contracts fail closed across human org mutations."""

from __future__ import annotations

import pytest

from chorus.errors import ActiveDelegationConflict
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Ledger,
    ManagementProfile,
    Task,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.testing import uid
from chorus.workforce import EmployeeStatus, LedgerWorkforce

pytestmark = pytest.mark.integration


def _seed_active_contract(ledger: Ledger) -> LedgerWorkforce:
    workforce = LedgerWorkforce(ledger.employees)
    workforce.hire(name="Boss", role="pm")
    workforce.hire(name="Lead", role="engineer", reports_to="boss")
    workforce.hire(name="Member", role="designer", reports_to="lead")
    workforce.hire(name="Other", role="pm", reports_to="boss")
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="lead",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=3,
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    ledger.teams.create(
        Team(
            id=uid("team-release"),
            name="Release",
            lead_employee_id="lead",
            status=TeamStatus.ACTIVE,
            created_by="user-admin",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("team-release"),
            employee_id="lead",
            membership_role=TeamMembershipRole.LEAD,
            source_manager_id="boss",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("team-release"),
            employee_id="member",
            source_manager_id="lead",
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("task-release"),
            intent="lead the release",
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("team-release"),
            assignee_employee_id="lead",
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("task-release"),
            team_id=uid("team-release"),
            lead_employee_id="lead",
            management_profile_version=1,
            max_depth=1,
            max_team_size=3,
            objective_rubric="integrate all release outcomes",
            status=DelegationContractStatus.DELEGATED,
        )
    )
    return workforce


def test_active_contract_blocks_lead_termination_without_mutation(ledger: Ledger) -> None:
    workforce = _seed_active_contract(ledger)

    with pytest.raises(ActiveDelegationConflict) as conflict:
        workforce.terminate("lead")

    assert conflict.value.task_ids == (uid("task-release"),)
    assert workforce.get("lead").status is EmployeeStatus.IDLE


def test_active_contract_blocks_member_reassignment_without_mutation(ledger: Ledger) -> None:
    workforce = _seed_active_contract(ledger)

    with pytest.raises(ActiveDelegationConflict):
        workforce.reassign("member", reports_to="other")

    assert workforce.get("member").reports_to == "lead"


def test_active_contract_blocks_profile_weakening_without_mutation(ledger: Ledger) -> None:
    _seed_active_contract(ledger)

    with pytest.raises(ActiveDelegationConflict):
        ledger.management_profiles.upsert(
            ManagementProfile(
                employee_id="lead",
                active=False,
                can_lead=False,
                max_delegation_depth=0,
                max_team_size=1,
                version=2,
                granted_by_user_id="user-admin",
            )
        )

    persisted = ledger.management_profiles.get("lead")
    assert persisted is not None
    assert (persisted.active, persisted.version) == (True, 1)


def test_terminal_contract_releases_reporting_termination_and_profile_guards(
    ledger: Ledger,
) -> None:
    workforce = _seed_active_contract(ledger)
    ledger.delegation_contracts.update_status(uid("task-release"), DelegationContractStatus.DONE)

    workforce.reassign("member", reports_to="other")
    workforce.terminate("lead")
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="lead",
            active=False,
            can_lead=False,
            max_delegation_depth=0,
            max_team_size=1,
            version=2,
            granted_by_user_id="user-admin",
        )
    )

    assert workforce.get("member").reports_to == "other"
    assert workforce.get("lead").status is EmployeeStatus.TERMINATED
    profile = ledger.management_profiles.get("lead")
    assert profile is not None and not profile.active and profile.version == 2
