# Generated by AI (UnitTest MCP unavailable in this session)
"""Typed, governed workforce formation from a CEO proposal."""

from __future__ import annotations

import pytest

from chorus.governance import WorkforcePlanService
from chorus.ledger import (
    Ledger,
    ManagementGrantDraft,
    PlannedEmployee,
    WorkforcePlanDraft,
    WorkforcePlanStatus,
)
from chorus.roles import RoleRegistry, default_roles
from chorus.workforce import Employee, EmployeeStatus, LedgerWorkforce

pytestmark = pytest.mark.integration


def _roles() -> RoleRegistry:
    return RoleRegistry.from_plugins(default_roles())


def _service(ledger: Ledger) -> WorkforcePlanService:
    return WorkforcePlanService(
        ledger,
        workforce=LedgerWorkforce(ledger.employees),
        roles=_roles(),
        max_org_depth=2,
    )


def _seed_ceo(ledger: Ledger) -> None:
    ledger.employees.create(
        Employee(id="ceo", name="CEO", role="ceo", status=EmployeeStatus.ACTIVE)
    )


def _draft() -> WorkforcePlanDraft:
    return WorkforcePlanDraft(
        rationale="A shallow functional company covers the approved first sprint.",
        confidence=0.84,
        source_goal_ids=("goal-feedback-triage",),
        employees=(
            PlannedEmployee(
                ref="product-lead",
                name="Product Lead",
                profession="pm",
                reports_to_ref="ceo",
                responsibilities=("Own product discovery and experience quality",),
            ),
            PlannedEmployee(
                ref="engineering-lead",
                name="Engineering Lead",
                profession="backend_engineer",
                reports_to_ref="ceo",
                responsibilities=("Own implementation architecture and delivery quality",),
            ),
            PlannedEmployee(
                ref="marketer",
                name="Launch Marketer",
                profession="marketer",
                reports_to_ref="ceo",
                responsibilities=("Own launch positioning",),
            ),
            PlannedEmployee(
                ref="designer",
                name="Product Designer",
                profession="designer",
                reports_to_ref="product-lead",
                responsibilities=("Design the triage workflow",),
            ),
            PlannedEmployee(
                ref="analyst",
                name="Feedback Analyst",
                profession="analyst",
                reports_to_ref="product-lead",
                responsibilities=("Analyze representative feedback",),
            ),
            PlannedEmployee(
                ref="frontend",
                name="Frontend Engineer",
                profession="frontend_engineer",
                reports_to_ref="engineering-lead",
                responsibilities=("Build the operator experience",),
            ),
            PlannedEmployee(
                ref="backend",
                name="Backend Engineer",
                profession="backend_engineer",
                reports_to_ref="engineering-lead",
                responsibilities=("Build feedback ingestion and triage",),
            ),
        ),
        management_grants=(
            ManagementGrantDraft(
                employee_ref="ceo",
                can_lead=True,
                can_subdelegate=True,
                max_delegation_depth=2,
                max_team_size=4,
                allowed_professions=("pm", "backend_engineer", "marketer"),
                spend_limit_cents=100_000,
            ),
            ManagementGrantDraft(
                employee_ref="product-lead",
                can_lead=True,
                can_subdelegate=True,
                max_delegation_depth=1,
                max_team_size=3,
                allowed_professions=("designer", "analyst"),
                spend_limit_cents=35_000,
            ),
            ManagementGrantDraft(
                employee_ref="engineering-lead",
                can_lead=True,
                can_subdelegate=True,
                max_delegation_depth=1,
                max_team_size=3,
                allowed_professions=("frontend_engineer", "backend_engineer"),
                spend_limit_cents=55_000,
            ),
        ),
    )


def test_ceo_proposal_is_typed_persisted_and_does_not_hire(ledger: Ledger) -> None:
    _seed_ceo(ledger)

    proposed = _service(ledger).propose(_draft(), proposed_by_employee_id="ceo")

    assert proposed.status is WorkforcePlanStatus.PROPOSED
    assert proposed.revision == 1
    assert proposed.proposed_by_employee_id == "ceo"
    assert ledger.workforce_plans.get(proposed.id, revision=1) == proposed
    assert [employee.id for employee in ledger.employees.list()] == ["ceo"]
    assert ledger.management_profiles.list() == []


def test_ceo_cannot_open_a_second_plan_while_one_awaits_human_decision(
    ledger: Ledger,
) -> None:
    _seed_ceo(ledger)
    service = _service(ledger)
    first = service.propose(_draft(), proposed_by_employee_id="ceo")

    with pytest.raises(ValueError, match="already has a proposed workforce plan"):
        service.propose(_draft(), proposed_by_employee_id="ceo")

    assert ledger.workforce_plans.list() == [first]
    proposal_activities = [
        activity
        for activity in ledger.activity.all()
        if activity.verb.value == "workforce_plan_proposed"
    ]
    assert len(proposal_activities) == 1


def test_human_rejection_closes_plan_without_materializing(
    ledger: Ledger,
) -> None:
    _seed_ceo(ledger)
    service = _service(ledger)
    plan = service.propose(_draft(), proposed_by_employee_id="ceo")

    rejected = service.reject(plan.id, rejected_by_user_id="founder")

    assert rejected.status is WorkforcePlanStatus.REJECTED
    assert rejected.decided_by_user_id == "founder"
    assert [employee.id for employee in ledger.employees.list()] == ["ceo"]
    with pytest.raises(ValueError, match="not proposed"):
        service.approve(plan.id, approved_by_user_id="founder")
    assert ledger.teams.list() == []


def test_human_can_revise_fields_then_atomically_apply_the_latest_plan(
    ledger: Ledger,
) -> None:
    _seed_ceo(ledger)
    service = _service(ledger)
    proposed = service.propose(_draft(), proposed_by_employee_id="ceo")
    revised_draft = WorkforcePlanDraft(
        **{
            **_draft().__dict__,
            "rationale": "Founder-approved responsibilities and tighter CEO spend.",
            "management_grants": (
                ManagementGrantDraft(
                    **{
                        **_draft().management_grants[0].__dict__,
                        "spend_limit_cents": 90_000,
                    }
                ),
                *_draft().management_grants[1:],
            ),
        }
    )

    revised = service.revise(
        proposed.id,
        revised_draft,
        revised_by_user_id="founder",
    )
    applied = service.approve(revised.id, approved_by_user_id="founder")

    assert revised.revision == 2
    assert applied.status is WorkforcePlanStatus.APPLIED
    assert applied.revision == 2
    assert applied.decided_by_user_id == "founder"
    assert (
        ledger.workforce_plans.get(applied.id, revision=1).status is WorkforcePlanStatus.SUPERSEDED
    )  # type: ignore[union-attr]
    assert len(ledger.employees.list()) == 8
    assert {employee.role for employee in ledger.employees.list()} == {
        "ceo",
        "pm",
        "designer",
        "analyst",
        "marketer",
        "frontend_engineer",
        "backend_engineer",
    }
    assert {profile.employee_id for profile in ledger.management_profiles.active_profiles()} == {
        "ceo",
        "product-lead",
        "engineering-lead",
    }
    assert ledger.management_profiles.get("ceo").spend_limit_cents == 90_000  # type: ignore[union-attr]
    assert ledger.employees.get("designer").reports_to == "product-lead"  # type: ignore[union-attr]
    assert ledger.employees.get("frontend").reports_to == "engineering-lead"  # type: ignore[union-attr]
    assert ledger.teams.list() == []


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        (
            lambda draft: WorkforcePlanDraft(
                **{
                    **draft.__dict__,
                    "employees": (
                        *draft.employees,
                        PlannedEmployee(
                            ref="too-deep",
                            name="Too Deep",
                            profession="analyst",
                            reports_to_ref="designer",
                        ),
                    ),
                }
            ),
            "depth",
        ),
        (
            lambda draft: WorkforcePlanDraft(
                **{
                    **draft.__dict__,
                    "employees": (
                        PlannedEmployee(
                            **{
                                **draft.employees[0].__dict__,
                                "profession": "engineer",
                            }
                        ),
                        *draft.employees[1:],
                    ),
                }
            ),
            "profession",
        ),
        (
            lambda draft: WorkforcePlanDraft(
                **{
                    **draft.__dict__,
                    "employees": (
                        PlannedEmployee(
                            **{
                                **draft.employees[0].__dict__,
                                "reports_to_ref": "designer",
                            }
                        ),
                        PlannedEmployee(
                            **{
                                **draft.employees[3].__dict__,
                                "reports_to_ref": "product-lead",
                            }
                        ),
                        *draft.employees[1:3],
                        *draft.employees[4:],
                    ),
                }
            ),
            "cycle",
        ),
    ],
)
def test_invalid_or_deep_plan_is_rejected_without_workforce_or_authority_writes(
    ledger: Ledger,
    mutate: object,
    message: str,
) -> None:
    _seed_ceo(ledger)
    invalid = mutate(_draft())  # type: ignore[operator]

    with pytest.raises(ValueError, match=message):
        _service(ledger).propose(invalid, proposed_by_employee_id="ceo")

    assert [employee.id for employee in ledger.employees.list()] == ["ceo"]
    assert ledger.management_profiles.list() == []
    assert ledger.workforce_plans.list() == []


def test_apply_rolls_back_every_hire_and_grant_when_audit_fails(
    ledger: Ledger, monkeypatch: pytest.MonkeyPatch
) -> None:
    _seed_ceo(ledger)
    service = _service(ledger)
    proposed = service.propose(_draft(), proposed_by_employee_id="ceo")

    def fail_audit(_: object) -> None:
        raise RuntimeError("audit unavailable")

    monkeypatch.setattr(ledger.activity, "append", fail_audit)

    with pytest.raises(RuntimeError, match="audit unavailable"):
        service.approve(proposed.id, approved_by_user_id="founder")

    assert [employee.id for employee in ledger.employees.list()] == ["ceo"]
    assert ledger.management_profiles.list() == []
    assert ledger.workforce_plans.latest(proposed.id).status is WorkforcePlanStatus.PROPOSED  # type: ignore[union-attr]


def test_apply_provisions_role_declared_routines_for_each_hire(ledger: Ledger) -> None:
    """OM-1, found live 2026-07-18: a formed org must heartbeat like a facade-hired one.
    Plan materialization creates employees directly, so it must run the same routine
    reconciliation hire() does — else the CEO's plan yields a dormant workforce."""
    _seed_ceo(ledger)
    service = _service(ledger)
    plan = service.propose(_draft(), proposed_by_employee_id="ceo")

    service.approve(plan.id, approved_by_user_id="user-founder")

    # The pm role declares a weekly planning routine; the materialized PM must carry it.
    routines = ledger.routines.list(employee_id="product-lead")
    assert {r.routine_key for r in routines} == {"pm-weekly-planning-review"}
    # And the backend engineer's two standing scans.
    engineer_keys = {r.routine_key for r in ledger.routines.list(employee_id="engineering-lead")}
    assert engineer_keys == {"backend-engineer-dependency-scan", "backend-engineer-slo-watch"}
