# Generated by AI (UnitTest MCP unavailable in this session)
"""Durable staffing requests and CEO workforce amendments."""

from __future__ import annotations

import asyncio

import pytest

from chorus.governance import StaffingRequestService, WorkforcePlanService
from chorus.heartbeat import BeatContext
from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Goal,
    Ledger,
    ManagementProfile,
    PlannedEmployee,
    StaffingNeed,
    StaffingRequestStatus,
    Task,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
    WorkforcePlanDraft,
    WorkforcePlanStatus,
)
from chorus.roles import RoleRegistry, default_roles
from chorus.testing import uid
from chorus.workforce import Employee, EmployeeStatus, LedgerWorkforce
from chorus_tools import StaffingRequestTool, WorkforceCatalogReadTool

pytestmark = pytest.mark.integration


def _roles() -> RoleRegistry:
    return RoleRegistry.from_plugins(default_roles())


def _seed(ledger: Ledger) -> None:
    ledger.employees.create(
        Employee(id="ceo", name="CEO", role="ceo", status=EmployeeStatus.ACTIVE)
    )
    ledger.employees.create(
        Employee(
            id=uid("engineering-lead"),
            name="Engineering Lead",
            role="backend_engineer",
            reports_to="ceo",
            status=EmployeeStatus.ACTIVE,
        )
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=uid("engineering-lead"),
            granted_by_user_id="founder",
            active=True,
            can_lead=True,
            can_subdelegate=False,
            max_delegation_depth=1,
            max_team_size=3,
            allowed_professions=("backend_engineer", "frontend_engineer"),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id=uid("team-engineering"),
            name="Mission: Feedback Triage",
            lead_employee_id=uid("engineering-lead"),
            created_by="ceo",
            status=TeamStatus.ACTIVE,
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("team-engineering"),
            employee_id=uid("engineering-lead"),
            source_manager_id="ceo",
            membership_role=TeamMembershipRole.LEAD,
        )
    )
    ledger.goals.create(Goal(id=uid("goal-feedback"), title="Ship feedback triage"))
    ledger.tasks.submit(
        Task(
            id=uid("root-engineering"),
            intent="Build feedback triage",
            goal_id=uid("goal-feedback"),
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("team-engineering"),
            assignee_employee_id=uid("engineering-lead"),
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("root-engineering"),
            team_id=uid("team-engineering"),
            lead_employee_id=uid("engineering-lead"),
            management_profile_version=1,
            can_subdelegate=False,
            max_depth=1,
            max_team_size=3,
            objective_rubric="Working feedback triage product",
            status=DelegationContractStatus.DELEGATED,
        )
    )


def _request(ledger: Ledger):
    return StaffingRequestService(ledger).request(
        task_id=uid("root-engineering"),
        requested_by_employee_id=uid("engineering-lead"),
        rationale="No frontend specialist exists for the interface deliverable.",
        needs=(StaffingNeed(profession="frontend_engineer", count=1),),
    )


def _ctx(working_dir):
    from dream.tools._context import ToolExecutionContext

    return ToolExecutionContext(
        working_dir=working_dir,
        session_id="sess",
        metadata={},
        scratch_dir=working_dir,
        cancel_requested=False,
    )


def test_lead_request_is_durable_and_does_not_hire(ledger: Ledger) -> None:
    _seed(ledger)

    request = _request(ledger)

    assert request.status is StaffingRequestStatus.OPEN
    assert request.goal_id == uid("goal-feedback")
    assert request.team_id == uid("team-engineering")
    assert ledger.staffing_requests.get(request.id) == request
    assert [employee.id for employee in ledger.employees.list()] == [
        "ceo",
        uid("engineering-lead"),
    ]


def test_non_lead_and_authority_expanding_requests_are_rejected(
    ledger: Ledger,
) -> None:
    _seed(ledger)

    with pytest.raises(ValueError, match="contract lead"):
        StaffingRequestService(ledger).request(
            task_id=uid("root-engineering"),
            requested_by_employee_id="ceo",
            rationale="Wrong actor",
            needs=(StaffingNeed("frontend_engineer"),),
        )
    with pytest.raises(ValueError, match="approved profession"):
        StaffingRequestService(ledger).request(
            task_id=uid("root-engineering"),
            requested_by_employee_id=uid("engineering-lead"),
            rationale="Would widen authority",
            needs=(StaffingNeed("designer"),),
        )
    assert ledger.staffing_requests.list() == []


def test_human_approval_atomically_fulfils_request_with_no_contract_rebind(
    ledger: Ledger,
) -> None:
    _seed(ledger)
    request = _request(ledger)
    service = WorkforcePlanService(
        ledger,
        workforce=LedgerWorkforce(ledger.employees),
        roles=_roles(),
        max_org_depth=2,
    )
    plan = service.propose(
        WorkforcePlanDraft(
            rationale="Fill the one approved frontend gap for the active goal.",
            confidence=0.9,
            source_goal_ids=(uid("goal-feedback"),),
            employees=(
                PlannedEmployee(
                    ref="frontend",
                    name="Frontend Engineer",
                    profession="frontend_engineer",
                    reports_to_ref=uid("engineering-lead"),
                ),
            ),
            management_grants=(),
        ),
        proposed_by_employee_id="ceo",
        staffing_request_id=request.id,
    )

    applied = service.approve(plan.id, approved_by_user_id="founder")

    assert applied.status is WorkforcePlanStatus.APPLIED
    assert ledger.employees.get("frontend").reports_to == uid("engineering-lead")  # type: ignore[union-attr]
    resolved = ledger.staffing_requests.get(request.id)
    assert resolved is not None and (
        resolved.status,
        resolved.workforce_plan_id,
    ) == (StaffingRequestStatus.FULFILLED, plan.id)
    profile = ledger.management_profiles.get(uid("engineering-lead"))
    contract = ledger.delegation_contracts.get(uid("root-engineering"))
    assert profile is not None and profile.version == 1
    assert contract is not None and contract.management_profile_version == 1
    assert ledger.team_members.members_of(uid("team-engineering"))[0].employee_id == uid(
        "engineering-lead"
    )


def test_amendment_must_exactly_cover_the_linked_request(ledger: Ledger) -> None:
    _seed(ledger)
    request = _request(ledger)
    service = WorkforcePlanService(
        ledger,
        workforce=LedgerWorkforce(ledger.employees),
        roles=_roles(),
    )
    draft = WorkforcePlanDraft(
        rationale="Wrong profession and manager.",
        confidence=0.9,
        source_goal_ids=(uid("goal-feedback"),),
        employees=(
            PlannedEmployee(
                ref="marketer",
                name="Marketer",
                profession="marketer",
                reports_to_ref="ceo",
            ),
        ),
        management_grants=(),
    )

    with pytest.raises(ValueError, match="exactly cover"):
        service.propose(
            draft,
            proposed_by_employee_id="ceo",
            staffing_request_id=request.id,
        )

    assert ledger.workforce_plans.list() == []
    assert ledger.staffing_requests.get(request.id) == request


def test_lead_tool_opens_request_and_ceo_catalog_surfaces_it(
    ledger: Ledger,
    tmp_path,
) -> None:
    _seed(ledger)
    BeatContext(
        task_id=uid("root-engineering"),
        run_id=uid("run-1"),
        employee_id=uid("engineering-lead"),
    ).write(tmp_path)

    result = asyncio.run(
        StaffingRequestTool(ledger).execute(
            {
                "rationale": "The active Team has no frontend specialist.",
                "needs": [{"profession": "frontend_engineer", "count": 1}],
            },
            _ctx(tmp_path),
        )
    )
    catalog = asyncio.run(WorkforceCatalogReadTool(ledger, _roles()).execute({}, _ctx(tmp_path)))

    assert result.is_error is False
    assert result.structured["status"] == "open"
    assert catalog.structured["open_staffing_requests"] == [
        {
            "request_id": result.structured["staffing_request_id"],
            "task_id": uid("root-engineering"),
            "goal_id": uid("goal-feedback"),
            "team_id": uid("team-engineering"),
            "requested_by_employee_id": uid("engineering-lead"),
            "rationale": "The active Team has no frontend specialist.",
            "needs": [{"profession": "frontend_engineer", "count": 1}],
        }
    ]
    assert [employee.id for employee in ledger.employees.list()] == [
        "ceo",
        uid("engineering-lead"),
    ]
