# Generated by AI (UnitTest MCP)
"""Human-governed management authority mutations."""

from __future__ import annotations

import pytest

from chorus.errors import ActiveDelegationConflict
from chorus.governance import ManagementAuthorityService
from chorus.ledger import (
    ActivityVerb,
    DelegationContract,
    DelegationContractStatus,
    ManagementProfile,
    SqliteLedger,
    Task,
    TaskStatus,
    Team,
    TeamMember,
    TeamStatus,
)
from chorus.roles import RoleRegistry, default_roles
from chorus.workforce import Employee

pytestmark = pytest.mark.integration


def _profile(*, granted_by_user_id: str = "spoofed-user") -> ManagementProfile:
    return ManagementProfile(
        employee_id="lead",
        active=True,
        can_lead=True,
        max_delegation_depth=2,
        max_team_size=4,
        allowed_professions=("backend_engineer",),
        version=1,
        granted_by_user_id=granted_by_user_id,
    )


def test_profile_grant_rejects_blank_human_actor_without_writes(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    service = ManagementAuthorityService(ledger)

    with pytest.raises(ValueError, match="actor_user_id"):
        service.upsert_profile(_profile(), actor_user_id="  ")

    assert (ledger.management_profiles.get("lead"), ledger.activity.all()) == (None, [])


def test_profile_grant_records_one_typed_human_audit(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    service = ManagementAuthorityService(ledger)

    granted = service.upsert_profile(_profile(), actor_user_id="user-admin")

    activity = ledger.activity.by_subject("management_profile", "lead")
    assert granted.granted_by_user_id == "user-admin"
    assert len(activity) == 1
    assert activity[0].verb is ActivityVerb.PROFILE_GRANTED
    assert activity[0].actor_user_id == "user-admin"
    assert activity[0].payload == {"version": 1}


def test_profile_grant_rolls_back_when_audit_fails(
    ledger: SqliteLedger, monkeypatch: pytest.MonkeyPatch
) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    service = ManagementAuthorityService(ledger)

    def fail_audit(_: object) -> None:
        raise RuntimeError("audit unavailable")

    monkeypatch.setattr(ledger.activity, "append", fail_audit)

    with pytest.raises(RuntimeError, match="audit unavailable"):
        service.upsert_profile(_profile(), actor_user_id="user-admin")

    assert ledger.management_profiles.get("lead") is None


def test_profile_deactivation_records_revocation_with_new_version(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    service = ManagementAuthorityService(ledger)
    service.upsert_profile(_profile(), actor_user_id="user-admin")

    deactivated = service.deactivate_profile("lead", actor_user_id="user-owner")

    activity = ledger.activity.by_subject("management_profile", "lead")
    assert (deactivated.active, deactivated.version) == (False, 2)
    assert [event.verb for event in activity] == [
        ActivityVerb.PROFILE_GRANTED,
        ActivityVerb.PROFILE_REVOKED,
    ]
    assert activity[-1].actor_user_id == "user-owner"
    assert activity[-1].payload == {"version": 2}


def test_profile_deactivation_refusal_is_atomic_and_audited(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    service = ManagementAuthorityService(ledger)
    service.upsert_profile(_profile(), actor_user_id="user-admin")
    ledger.tasks.submit(Task(id="task-release", intent="Lead the release"))
    ledger.teams.create(
        Team(id="team-release", name="Release", lead_employee_id="lead", created_by="seed")
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id="task-release",
            team_id="team-release",
            lead_employee_id="lead",
            management_profile_version=1,
            max_depth=1,
            max_team_size=3,
            objective_rubric="Release is integrated",
            status=DelegationContractStatus.DELEGATED,
        )
    )

    with pytest.raises(ActiveDelegationConflict) as conflict:
        service.deactivate_profile("lead", actor_user_id="user-owner")

    profile = ledger.management_profiles.get("lead")
    refusal = ledger.activity.by_subject("management_profile", "lead")[-1]
    assert profile is not None and (profile.active, profile.version) == (True, 1)
    assert conflict.value.task_ids == ("task-release",)
    assert refusal.verb is ActivityVerb.REORG_REFUSED
    assert refusal.actor_user_id == "user-owner"
    assert refusal.payload == {
        "operation": "deactivate_profile",
        "contract_task_ids": ["task-release"],
        "team_ids": ["team-release"],
    }


def test_team_create_and_archive_are_human_governed_and_audited(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    service = ManagementAuthorityService(ledger)

    created = service.create_team(
        Team(id="team-release", name="Release", lead_employee_id="lead", created_by="spoofed"),
        actor_user_id="user-admin",
    )
    archived = service.archive_team("team-release", actor_user_id="user-owner")

    activity = ledger.activity.by_subject("team", "team-release")
    assert created.created_by == "user-admin"
    assert archived.status is TeamStatus.ARCHIVED
    assert [event.verb for event in activity] == [
        ActivityVerb.TEAM_FORMED,
        ActivityVerb.TEAM_ARCHIVED,
    ]
    assert [event.actor_user_id for event in activity] == ["user-admin", "user-owner"]


def test_team_membership_mutations_emit_typed_human_audits(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    ledger.employees.create(Employee(id="member", name="Member", role="designer"))
    ledger.teams.create(
        Team(id="team-release", name="Release", lead_employee_id="lead", created_by="seed")
    )
    service = ManagementAuthorityService(ledger)

    service.add_team_member(
        TeamMember(team_id="team-release", employee_id="member", source_manager_id="lead"),
        actor_user_id="user-admin",
    )
    removed = service.remove_team_member(
        "team-release", "member", actor_user_id="user-admin"
    )

    activity = ledger.activity.by_subject("team_member", "team-release/member")
    assert removed.left_at is not None
    assert [event.verb for event in activity] == [
        ActivityVerb.TEAM_MEMBER_ADDED,
        ActivityVerb.TEAM_MEMBER_REMOVED,
    ]
    assert all(event.actor_user_id == "user-admin" for event in activity)


def test_delegation_contract_mutations_emit_typed_human_audits(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    ledger.tasks.submit(Task(id="task-release", intent="Lead the release"))
    ledger.teams.create(
        Team(id="team-release", name="Release", lead_employee_id="lead", created_by="seed")
    )
    service = ManagementAuthorityService(ledger)

    service.create_delegation_contract(
        DelegationContract(
            task_id="task-release",
            team_id="team-release",
            lead_employee_id="lead",
            management_profile_version=1,
            max_depth=1,
            max_team_size=3,
            objective_rubric="All delegated outcomes are integrated",
        ),
        actor_user_id="user-admin",
    )
    delegated = service.update_delegation_contract_status(
        "task-release",
        DelegationContractStatus.DELEGATED,
        actor_user_id="user-admin",
    )

    activity = ledger.activity.by_subject("delegation_contract", "task-release")
    assert delegated.status is DelegationContractStatus.DELEGATED
    assert [event.verb for event in activity] == [
        ActivityVerb.DELEGATION_CREATED,
        ActivityVerb.DELEGATION_STATUS_CHANGED,
    ]
    assert activity[-1].payload == {"status": "delegated"}


def _specialization_profile() -> ManagementProfile:
    return ManagementProfile(
        employee_id="legacy-manager",
        granted_by_user_id="spoofed",
        active=True,
        can_lead=True,
        can_subdelegate=True,
        max_delegation_depth=2,
        max_team_size=4,
        allowed_professions=("backend_engineer",),
        spend_limit_cents=50_000,
    )


def _roles() -> RoleRegistry:
    return RoleRegistry.from_plugins(default_roles())


def test_specialize_manager_preserves_identity_org_budget_memory_and_history(
    ledger: SqliteLedger,
) -> None:
    ledger.employees.create(Employee(id="root", name="Root", role="ceo"))
    ledger.employees.create(
        Employee(
            id="legacy-manager",
            name="Legacy Manager",
            role="manager",
            reports_to="root",
            memory_scope="organization",
            budget_monthly_cents=80_000,
            spent_monthly_cents=12_345,
            last_beat_at="2026-07-13T12:00:00+00:00",
        )
    )
    ledger.employees.create(
        Employee(id="report", name="Report", role="designer", reports_to="legacy-manager")
    )
    before_activity = tuple(ledger.activity.all())

    profile = ManagementAuthorityService(ledger).specialize_manager(
        "legacy-manager",
        profession="backend_engineer",
        profile=_specialization_profile(),
        roles=_roles(),
        actor_user_id="operator-1",
    )

    employee = ledger.employees.get("legacy-manager")
    report = ledger.employees.get("report")
    assert employee is not None and report is not None
    assert employee.id == "legacy-manager" and employee.role == "backend_engineer"
    assert employee.reports_to == "root" and report.reports_to == "legacy-manager"
    assert employee.memory_scope == "organization"
    assert (employee.budget_monthly_cents, employee.spent_monthly_cents) == (80_000, 12_345)
    assert employee.last_beat_at == "2026-07-13T12:00:00+00:00"
    assert profile.active is True and profile.granted_by_user_id == "operator-1"
    audit = ledger.activity.by_subject("management_profile", "legacy-manager")
    assert tuple(ledger.activity.all()[: len(before_activity)]) == before_activity
    assert len(audit) == 1 and audit[0].verb is ActivityVerb.PROFILE_GRANTED
    assert audit[0].payload == {"profession": "backend_engineer", "version": 1}


@pytest.mark.parametrize("profession", ["missing-role", "manager"])
def test_specialize_manager_rejects_unknown_or_ambiguous_profession_without_writes(
    ledger: SqliteLedger, profession: str
) -> None:
    ledger.employees.create(Employee(id="legacy-manager", name="Legacy", role="manager"))

    with pytest.raises(ValueError, match="profession"):
        ManagementAuthorityService(ledger).specialize_manager(
            "legacy-manager",
            profession=profession,
            profile=_specialization_profile(),
            roles=_roles(),
            actor_user_id="operator-1",
        )

    assert ledger.employees.get("legacy-manager").role == "manager"  # type: ignore[union-attr]
    assert ledger.management_profiles.get("legacy-manager") is None
    assert ledger.activity.all() == []


def test_specialize_manager_rejects_non_manager_without_writes(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="specialist", name="Specialist", role="designer"))
    profile = ManagementProfile(
        **{**_specialization_profile().__dict__, "employee_id": "specialist"}
    )

    with pytest.raises(ValueError, match="role='manager'"):
        ManagementAuthorityService(ledger).specialize_manager(
            "specialist",
            profession="backend_engineer",
            profile=profile,
            roles=_roles(),
            actor_user_id="operator-1",
        )

    assert ledger.employees.get("specialist").role == "designer"  # type: ignore[union-attr]
    assert ledger.management_profiles.get("specialist") is None


def test_specialize_manager_rejects_all_nonterminal_assigned_work(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="legacy-manager", name="Legacy", role="manager"))
    for status in (TaskStatus.BACKLOG, TaskStatus.TODO, TaskStatus.BLOCKED):
        ledger.tasks.submit(
            Task(
                id=f"task-{status.value}",
                intent="Unresolved work",
                status=status,
                assignee_employee_id="legacy-manager",
            )
        )

    with pytest.raises(ValueError, match="active work"):
        ManagementAuthorityService(ledger).specialize_manager(
            "legacy-manager",
            profession="backend_engineer",
            profile=_specialization_profile(),
            roles=_roles(),
            actor_user_id="operator-1",
        )

    assert ledger.employees.get("legacy-manager").role == "manager"  # type: ignore[union-attr]
    assert ledger.management_profiles.get("legacy-manager") is None


def test_specialize_manager_rolls_back_role_and_profile_when_audit_fails(
    ledger: SqliteLedger, monkeypatch: pytest.MonkeyPatch
) -> None:
    ledger.employees.create(Employee(id="legacy-manager", name="Legacy", role="manager"))

    def fail_audit(_: object) -> None:
        raise RuntimeError("audit unavailable")

    monkeypatch.setattr(ledger.activity, "append", fail_audit)

    with pytest.raises(RuntimeError, match="audit unavailable"):
        ManagementAuthorityService(ledger).specialize_manager(
            "legacy-manager",
            profession="backend_engineer",
            profile=_specialization_profile(),
            roles=_roles(),
            actor_user_id="operator-1",
        )

    assert ledger.employees.get("legacy-manager").role == "manager"  # type: ignore[union-attr]
    assert ledger.management_profiles.get("legacy-manager") is None
