# Generated by AI (UnitTest MCP)
"""M8 management authority persistence contracts."""

from __future__ import annotations

import pytest

from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    ManagementProfile,
    SqliteLedger,
    Task,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.workforce import Employee

pytestmark = pytest.mark.integration


def test_task_defaults_to_delivery_without_a_team() -> None:
    task = Task(id="task-delivery", intent="ship the feature")

    assert (task.execution_mode, task.team_id) == (ExecutionMode.DELIVERY, None)


def test_delegation_task_execution_contract_round_trips(ledger: SqliteLedger) -> None:
    ledger.tasks.submit(
        Task(
            id="task-delegation",
            intent="lead the release",
            execution_mode=ExecutionMode.DELEGATION,
            team_id="team-release",
        )
    )

    persisted = ledger.tasks.get("task-delegation")

    assert persisted is not None
    assert (persisted.execution_mode, persisted.team_id) == (
        ExecutionMode.DELEGATION,
        "team-release",
    )


@pytest.mark.parametrize(
    "field,value",
    [
        ("version", 0),
        ("max_delegation_depth", -1),
        ("max_team_size", 0),
        ("spend_limit_cents", -1),
    ],
)
def test_management_profile_rejects_unbounded_authority(field: str, value: int) -> None:
    values: dict[str, object] = {
        "employee_id": "lead",
        "granted_by_user_id": "user-admin",
        field: value,
    }

    with pytest.raises(ValueError):
        ManagementProfile(**values)  # type: ignore[arg-type]


def test_management_profile_revisions_are_monotonic_and_round_trip(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    first = ManagementProfile(
        employee_id="lead",
        active=True,
        can_lead=True,
        can_subdelegate=True,
        max_delegation_depth=2,
        max_team_size=4,
        allowed_professions=("engineer", "designer"),
        spend_limit_cents=25_000,
        version=1,
        granted_by_user_id="user-admin",
    )
    ledger.management_profiles.upsert(first)

    with pytest.raises(ValueError, match="version"):
        ledger.management_profiles.upsert(first)

    second = ledger.management_profiles.upsert(
        ManagementProfile(
            **{
                **first.__dict__,
                "max_team_size": 5,
                "version": 2,
            }
        )
    )

    assert second == ledger.management_profiles.get("lead")


def test_authority_graph_round_trips_with_pinned_profile_version(ledger: SqliteLedger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    ledger.employees.create(
        Employee(id="member", name="Member", role="designer", reports_to="lead")
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id="lead",
            active=True,
            can_lead=True,
            max_team_size=3,
            allowed_professions=("designer",),
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    ledger.teams.create(
        Team(
            id="team-release",
            name="Release",
            lead_employee_id="lead",
            status=TeamStatus.ACTIVE,
            created_by="user-admin",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id="team-release",
            employee_id="lead",
            membership_role=TeamMembershipRole.LEAD,
            source_manager_id="lead",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id="team-release",
            employee_id="member",
            source_manager_id="lead",
        )
    )
    ledger.tasks.submit(
        Task(
            id="task-release",
            intent="lead the release",
            execution_mode=ExecutionMode.DELEGATION,
            team_id="team-release",
            assignee_employee_id="lead",
        )
    )
    created = ledger.delegation_contracts.create(
        DelegationContract(
            task_id="task-release",
            team_id="team-release",
            lead_employee_id="lead",
            management_profile_version=1,
            can_subdelegate=False,
            max_depth=1,
            max_team_size=3,
            spend_limit_cents=20_000,
            objective_rubric="all delegated outcomes are integrated",
            status=DelegationContractStatus.DELEGATED,
        )
    )

    persisted_members = ledger.team_members.members_of("team-release")

    assert ledger.teams.get("team-release") is not None
    assert {member.employee_id for member in persisted_members} == {"lead", "member"}
    assert ledger.delegation_contracts.get("task-release") == created
    assert created.management_profile_version == 1