# Generated by AI (UnitTest MCP)
"""M8 management authority persistence contracts."""

from __future__ import annotations

import pytest

from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Ledger,
    ManagementProfile,
    Task,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.testing import uid
from chorus.workforce import Employee

pytestmark = pytest.mark.integration


def test_task_defaults_to_delivery_without_a_team() -> None:
    task = Task(id=uid("task-delivery"), intent="ship the feature")

    assert (task.execution_mode, task.team_id) == (ExecutionMode.DELIVERY, None)


def test_delegation_task_execution_contract_round_trips(ledger: Ledger) -> None:
    ledger.tasks.submit(
        Task(
            id=uid("task-delegation"),
            intent="lead the release",
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("team-release"),
        )
    )

    persisted = ledger.tasks.get(uid("task-delegation"))

    assert persisted is not None
    assert (persisted.execution_mode, persisted.team_id) == (
        ExecutionMode.DELEGATION,
        uid("team-release"),
    )


@pytest.mark.parametrize(
    "field,value",
    [
        ("version", 0),
        ("max_delegation_depth", -1),
        ("max_team_size", 0),
        ("spend_limit_cents", -1),
    ],
)
def test_management_profile_rejects_unbounded_authority(field: str, value: int) -> None:
    values: dict[str, object] = {
        "employee_id": uid("lead"),
        "granted_by_user_id": "user-admin",
        field: value,
    }

    with pytest.raises(ValueError):
        ManagementProfile(**values)  # type: ignore[arg-type]


def test_management_profile_revisions_are_monotonic_and_round_trip(ledger: Ledger) -> None:
    ledger.employees.create(Employee(id=uid("lead"), name="Lead", role="engineer"))
    first = ManagementProfile(
        employee_id=uid("lead"),
        active=True,
        can_lead=True,
        can_subdelegate=True,
        max_delegation_depth=2,
        max_team_size=4,
        allowed_professions=("engineer", "designer"),
        spend_limit_cents=25_000,
        version=1,
        granted_by_user_id="user-admin",
    )
    ledger.management_profiles.upsert(first)

    with pytest.raises(ValueError, match="version"):
        ledger.management_profiles.upsert(first)

    second = ledger.management_profiles.upsert(
        ManagementProfile(
            **{
                **first.__dict__,
                "max_team_size": 5,
                "version": 2,
            }
        )
    )

    assert second == ledger.management_profiles.get(uid("lead"))


def test_authority_graph_round_trips_with_pinned_profile_version(ledger: Ledger) -> None:
    ledger.employees.create(Employee(id=uid("lead"), name="Lead", role="engineer"))
    ledger.employees.create(
        Employee(id=uid("member"), name="Member", role="designer", reports_to=uid("lead"))
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=uid("lead"),
            active=True,
            can_lead=True,
            max_team_size=3,
            allowed_professions=("designer",),
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    ledger.teams.create(
        Team(
            id=uid("team-release"),
            name="Release",
            lead_employee_id=uid("lead"),
            status=TeamStatus.ACTIVE,
            created_by="user-admin",
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("team-release"),
            employee_id=uid("lead"),
            membership_role=TeamMembershipRole.LEAD,
            source_manager_id=uid("lead"),
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("team-release"),
            employee_id=uid("member"),
            source_manager_id=uid("lead"),
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("task-release"),
            intent="lead the release",
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("team-release"),
            assignee_employee_id=uid("lead"),
        )
    )
    created = ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("task-release"),
            team_id=uid("team-release"),
            lead_employee_id=uid("lead"),
            management_profile_version=1,
            can_subdelegate=False,
            max_depth=1,
            max_team_size=3,
            max_direct_children=2,
            spend_limit_cents=20_000,
            objective_rubric="all delegated outcomes are integrated",
            status=DelegationContractStatus.DELEGATED,
        )
    )

    persisted_members = ledger.team_members.members_of(uid("team-release"))

    assert ledger.teams.get(uid("team-release")) is not None
    assert {member.employee_id for member in persisted_members} == {uid("lead"), uid("member")}
    assert ledger.delegation_contracts.get(uid("task-release")) == created
    assert created.management_profile_version == 1
    assert created.max_direct_children == 2
