# Generated by AI (UnitTest MCP)
"""Least-privilege authority intersection."""

from __future__ import annotations

import itertools

import pytest

from chorus.lifecycle import AuthorityIntersection, AuthorityLimits

pytestmark = pytest.mark.unit


@pytest.mark.parametrize(
    "depths,team_sizes",
    tuple(
        itertools.product(
            itertools.product((1, 2, 5), repeat=4),
            itertools.product((1, 3, 8), repeat=4),
        )
    ),
)
def test_effective_numeric_authority_never_exceeds_any_layer(
    depths: tuple[int, ...], team_sizes: tuple[int, ...]
) -> None:
    layers = tuple(
        AuthorityLimits(max_depth=depth, max_team_size=team_size)
        for depth, team_size in zip(depths, team_sizes, strict=True)
    )

    effective = AuthorityIntersection.intersect(*layers)

    assert effective.max_depth == min(depths)
    assert effective.max_team_size == min(team_sizes)
    assert all(effective.max_depth <= layer.max_depth for layer in layers)
    assert all(effective.max_team_size <= layer.max_team_size for layer in layers)


@pytest.mark.parametrize(
    "spend_limits,expected",
    [
        ((None, None, None), None),
        ((None, 10_000, None), 10_000),
        ((50_000, 10_000, 25_000), 10_000),
        ((0, None, 1_000), 0),
    ],
)
def test_spend_intersection_treats_none_as_uncapped(
    spend_limits: tuple[int | None, ...], expected: int | None
) -> None:
    layers = tuple(
        AuthorityLimits(max_depth=5, max_team_size=5, spend_limit_cents=limit)
        for limit in spend_limits
    )

    assert AuthorityIntersection.intersect(*layers).spend_limit_cents == expected


def test_allowed_professions_are_intersected_without_widening() -> None:
    effective = AuthorityIntersection.intersect(
        AuthorityLimits(5, 5, allowed_professions=frozenset()),
        AuthorityLimits(4, 4, allowed_professions=frozenset({"engineer", "designer"})),
        AuthorityLimits(3, 3, allowed_professions=frozenset({"designer", "pm"})),
    )

    assert effective.allowed_professions == frozenset({"designer"})


@pytest.mark.parametrize(
    "grants,expected",
    [
        ((True, True, True), True),
        ((False, True, True), False),
        ((True, False, True), False),
        ((True, True, False), False),
    ],
)
def test_subdelegation_requires_every_layer(grants: tuple[bool, ...], expected: bool) -> None:
    layers = tuple(AuthorityLimits(5, 5, can_subdelegate=grant) for grant in grants)

    assert AuthorityIntersection.intersect(*layers).can_subdelegate is expected
