# Generated by AI (UnitTest MCP)
"""Per-goal Mission Team policy."""

from __future__ import annotations

import pytest

from chorus.ledger import (
    ActivityVerb,
    Goal,
    ManagementProfile,
    SqliteLedger,
    TeamMembershipRole,
    TeamStatus,
)
from chorus.lifecycle import MissionTeamPolicy, MissionTeamPolicyDenied
from chorus.workforce import Employee, EmployeeStatus

pytestmark = pytest.mark.integration


def _seed_lead(ledger: SqliteLedger) -> Employee:
    lead = Employee(id="lead", name="Lead", role="engineer")
    ledger.employees.create(lead)
    ledger.goals.create(Goal(id="goal-release", title="Release"))
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            active=True,
            can_lead=True,
            max_delegation_depth=2,
            max_team_size=4,
            allowed_professions=("designer",),
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    return lead


def test_create_for_root_forms_one_audited_team_with_lead(ledger: SqliteLedger) -> None:
    lead = _seed_lead(ledger)
    policy = MissionTeamPolicy(ledger)

    first = policy.create_for_root(lead, "goal-release")
    repeated = policy.create_for_root(lead, "goal-release")

    members = ledger.team_members.members_of(first.id)
    team_activity = ledger.activity.by_subject("team", first.id)
    lead_activity = ledger.activity.by_subject("team_member", f"{first.id}/{lead.id}")
    assert repeated == first
    assert (first.goal_id, first.status) == ("goal-release", TeamStatus.FORMING)
    assert [(member.employee_id, member.membership_role) for member in members] == [
        (lead.id, TeamMembershipRole.LEAD)
    ]
    assert [event.verb for event in team_activity] == [ActivityVerb.TEAM_FORMED]
    assert [event.verb for event in lead_activity] == [ActivityVerb.TEAM_MEMBER_ADDED]
    assert team_activity[0].actor_employee_id is None
    assert team_activity[0].actor_user_id is None


def test_create_for_root_rejects_lead_without_active_lead_profile(ledger: SqliteLedger) -> None:
    lead = Employee(id="lead", name="Lead", role="engineer")
    ledger.employees.create(lead)
    policy = MissionTeamPolicy(ledger)

    with pytest.raises(MissionTeamPolicyDenied, match="active lead profile"):
        policy.create_for_root(lead, "goal-release")

    assert (ledger.teams.list_active(), ledger.activity.all()) == ([], [])


@pytest.mark.parametrize(
    "candidate",
    [
        Employee(id="cross-line", name="Cross Line", role="designer"),
        Employee(id="wrong-craft", name="Wrong Craft", role="pm", reports_to="lead"),
        Employee(
            id="pending",
            name="Pending",
            role="designer",
            reports_to="lead",
            status=EmployeeStatus.PENDING,
        ),
    ],
)
def test_validate_membership_rejects_out_of_policy_candidates(
    ledger: SqliteLedger, candidate: Employee
) -> None:
    lead = _seed_lead(ledger)
    ledger.employees.create(candidate)
    policy = MissionTeamPolicy(ledger)
    team = policy.create_for_root(lead, "goal-release")

    assert policy.validate_membership(team.id, candidate.id) is False


def test_add_member_accepts_active_allowed_direct_report_and_audits(ledger: SqliteLedger) -> None:
    lead = _seed_lead(ledger)
    member = Employee(id="member", name="Member", role="designer", reports_to=lead.id)
    ledger.employees.create(member)
    policy = MissionTeamPolicy(ledger)
    team = policy.create_for_root(lead, "goal-release")

    added = policy.add_member(team.id, member.id)

    activity = ledger.activity.by_subject("team_member", f"{team.id}/{member.id}")
    assert added.employee_id == member.id
    assert [event.verb for event in activity] == [ActivityVerb.TEAM_MEMBER_ADDED]


def test_add_member_rejection_has_no_partial_membership_or_audit(ledger: SqliteLedger) -> None:
    lead = _seed_lead(ledger)
    outsider = Employee(id="outsider", name="Outsider", role="designer")
    ledger.employees.create(outsider)
    policy = MissionTeamPolicy(ledger)
    team = policy.create_for_root(lead, "goal-release")

    with pytest.raises(MissionTeamPolicyDenied, match="membership"):
        policy.add_member(team.id, outsider.id)

    assert ledger.team_members.get(team.id, outsider.id) is None
    assert ledger.activity.by_subject("team_member", f"{team.id}/{outsider.id}") == []


def test_activate_and_archive_are_audited_and_idempotent(ledger: SqliteLedger) -> None:
    lead = _seed_lead(ledger)
    policy = MissionTeamPolicy(ledger)
    team = policy.create_for_root(lead, "goal-release")

    active = policy.activate(team.id)
    repeated_active = policy.activate(team.id)
    archived = policy.archive(team.id)
    repeated_archive = policy.archive(team.id)

    activity = ledger.activity.by_subject("team", team.id)
    assert (active.status, repeated_active.status) == (TeamStatus.ACTIVE, TeamStatus.ACTIVE)
    assert (archived.status, repeated_archive.status) == (
        TeamStatus.ARCHIVED,
        TeamStatus.ARCHIVED,
    )
    assert [event.verb for event in activity] == [
        ActivityVerb.TEAM_FORMED,
        ActivityVerb.TEAM_ACTIVATED,
        ActivityVerb.TEAM_ARCHIVED,
    ]
