# Generated by AI (UnitTest MCP)
"""Authorized delegation-mode capability mutations."""

from __future__ import annotations

from dataclasses import replace

import pytest

from chorus.ledger import (
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Goal,
    Ledger,
    ManagementProfile,
    Task,
    TaskStatus,
    TeamStatus,
)
from chorus.lifecycle import (
    DEFAULT_REQUEST_DEPTH_CAP,
    CapabilityService,
    ChildPlan,
    MissionTeamPolicy,
)
from chorus.testing import uid
from chorus.workforce import Employee

pytestmark = pytest.mark.integration


def _seed_delegation_parent(
    ledger: Ledger,
    *,
    can_subdelegate: bool = True,
    max_depth: int = 3,
    max_team_size: int = 3,
    max_direct_children: int | None = None,
    profile_spend_limit_cents: int = 20_000,
    contract_spend_limit_cents: int = 20_000,
) -> tuple[CapabilityService, Task]:
    lead = Employee(id="lead", name="Lead", role="engineer")
    member = Employee(id=uid("member"), name="Member", role="designer", reports_to=lead.id)
    ledger.employees.create(lead)
    ledger.employees.create(member)
    ledger.employees.create(Employee(id=uid("forger"), name="Forger", role="pm"))
    ledger.goals.create(Goal(id=uid("goal-release"), title="Release"))
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            active=True,
            can_lead=True,
            can_subdelegate=can_subdelegate,
            max_delegation_depth=max(3, max_depth),
            max_team_size=max_team_size,
            allowed_professions=("designer",),
            spend_limit_cents=profile_spend_limit_cents,
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=member.id,
            active=True,
            can_lead=True,
            can_subdelegate=True,
            max_delegation_depth=2,
            max_team_size=2,
            allowed_professions=("engineer",),
            spend_limit_cents=10_000,
            version=1,
            granted_by_user_id="user-admin",
        )
    )
    policy = MissionTeamPolicy(ledger)
    team = policy.create_for_root(lead, uid("goal-release"))
    policy.activate(team.id)
    parent = Task(
        id=uid("task-root"),
        intent="Lead the release",
        status=TaskStatus.TODO,
        execution_mode=ExecutionMode.DELEGATION,
        team_id=team.id,
        assignee_employee_id=lead.id,
        goal_id=uid("goal-release"),
    )
    ledger.tasks.submit(parent)
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=parent.id,
            team_id=team.id,
            lead_employee_id=lead.id,
            management_profile_version=1,
            can_subdelegate=can_subdelegate,
            max_depth=max_depth,
            max_team_size=max_team_size,
            max_direct_children=max_direct_children,
            spend_limit_cents=contract_spend_limit_cents,
            objective_rubric="All release outcomes are integrated",
            status=DelegationContractStatus.DELEGATED,
        )
    )
    return CapabilityService(ledger), parent


def _seed_delivery_parent(ledger: Ledger) -> tuple[CapabilityService, Task]:
    lead = Employee(id=uid("delivery-lead"), name="Delivery Lead", role="engineer")
    report = Employee(
        id=uid("delivery-report"),
        name="Delivery Report",
        role="designer",
        reports_to=lead.id,
    )
    ledger.employees.create(lead)
    ledger.employees.create(report)
    parent = Task(
        id=uid("delivery-parent"),
        intent="Build the release",
        status=TaskStatus.TODO,
        execution_mode=ExecutionMode.DELIVERY,
        assignee_employee_id=lead.id,
    )
    ledger.tasks.submit(parent)
    return CapabilityService(ledger), parent


def _start_integrating(ledger: Ledger, parent: Task) -> None:
    ledger.delegation_contracts.update_status(parent.id, DelegationContractStatus.INTEGRATING)


def test_decompose_rejects_delivery_parent_without_partial_writes(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delivery_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision="forged-delivery-decompose",
        actor_employee_id=uid("delivery-lead"),
        children=[ChildPlan(label="design", intent="Design", assignee=uid("delivery-report"))],
    )

    assert result.authority_denied == "management mutations require a delegation task"
    assert ledger.tasks.children(parent.id) == []


def test_submit_one_rejects_delivery_parent_without_partial_writes(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delivery_parent(ledger)

    result = service.submit_one(
        parent_id=parent.id,
        revision="forged-delivery-submit",
        actor_employee_id=uid("delivery-lead"),
        child=ChildPlan(label="design", intent="Design", assignee=uid("delivery-report")),
    )

    assert result.authority_denied == "management mutations require a delegation task"
    assert ledger.tasks.children(parent.id) == []


def test_reassign_rejects_delivery_parent_without_changing_assignment(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delivery_parent(ledger)
    child = ledger.tasks.submit(
        Task(
            id=uid("delivery-child"),
            intent="Existing child",
            status=TaskStatus.TODO,
            parent_id=parent.id,
            assignee_employee_id=uid("delivery-lead"),
        )
    )

    result = service.reassign(
        parent_id=parent.id,
        task_id=child.id,
        assignee=uid("delivery-report"),
        assigned_by=uid("delivery-lead"),
    )

    assert result.authority_denied == "management mutations require a delegation task"
    assert ledger.tasks.get(child.id).assignee_employee_id == uid("delivery-lead")


def test_decompose_rejects_forged_actor_without_partial_writes(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision="forged-run",
        actor_employee_id=uid("forger"),
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.authority_denied == "actor is not the delegation contract lead"
    assert ledger.tasks.children(parent.id) == []


def test_decompose_rejects_integrating_contract_without_partial_writes(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    ledger.delegation_contracts.update_status(parent.id, DelegationContractStatus.INTEGRATING)

    result = service.decompose(
        parent_id=parent.id,
        revision="late-decompose",
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.authority_denied == "decompose requires delegated contract phase"
    assert ledger.tasks.children(parent.id) == []


def test_corrective_mutations_reject_delegated_contract_phase(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    existing = ledger.tasks.submit(
        Task(
            id=uid("existing-child"),
            intent="Existing child",
            parent_id=parent.id,
            assignee_employee_id="lead",
        )
    )

    submitted = service.submit_one(
        parent_id=parent.id,
        revision="early-submit",
        actor_employee_id="lead",
        child=ChildPlan(label="correction", intent="Correct", assignee=uid("member")),
    )
    reassigned = service.reassign(
        parent_id=parent.id,
        task_id=existing.id,
        assignee=uid("member"),
        assigned_by="lead",
    )

    assert submitted.authority_denied == "corrective mutation requires integrating contract phase"
    assert reassigned.authority_denied == "corrective mutation requires integrating contract phase"
    assert ledger.tasks.get(existing.id).assignee_employee_id == "lead"
    assert [task.id for task in ledger.tasks.children(parent.id)] == [existing.id]
    assert ledger.team_members.get(parent.team_id or "", uid("member")) is None


def test_decompose_rejects_stale_profile_without_partial_writes(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)
    current = ledger.management_profiles.get("lead")
    assert current is not None
    ledger.management_profiles.upsert(replace(current, version=2, max_team_size=4))

    result = service.decompose(
        parent_id=parent.id,
        revision="stale-run",
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.authority_denied == "management profile version is stale"
    assert ledger.tasks.children(parent.id) == []


def test_decompose_persists_delivery_mode_and_adds_team_membership(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision=uid("delivery-run"),
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    child = ledger.tasks.get(result.child_ids["design"])
    assert result.authority_denied is None
    assert child is not None and child.execution_mode is ExecutionMode.DELIVERY
    assert ledger.team_members.get(parent.team_id or "", uid("member")) is not None


def test_decompose_creates_nested_team_and_contract_atomically(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision=uid("nested-run"),
        actor_employee_id="lead",
        children=[
            ChildPlan(
                label="design-area",
                intent="Lead design",
                assignee=uid("member"),
                execution_mode=ExecutionMode.DELEGATION,
                can_subdelegate=True,
            )
        ],
    )

    child = ledger.tasks.get(result.child_ids["design-area"])
    assert result.authority_denied is None
    assert child is not None and child.execution_mode is ExecutionMode.DELEGATION
    assert child.team_id is not None
    nested_team = ledger.teams.get(child.team_id)
    nested_contract = ledger.delegation_contracts.get(child.id)
    assert nested_team is not None and nested_team.status is TeamStatus.ACTIVE
    assert nested_team.parent_team_id == parent.team_id
    assert nested_contract is not None
    assert nested_contract.parent_contract_task_id == parent.id
    assert nested_contract.max_depth == 2
    assert nested_contract.max_team_size == 2
    assert nested_contract.spend_limit_cents == 10_000
    membership = ledger.team_members.get(parent.team_id or "", uid("member"))
    assert membership is not None and membership.can_subdelegate is True


def test_nested_delegation_without_explicit_team_grant_refuses_whole_wave(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision="missing-team-grant",
        actor_employee_id="lead",
        children=[
            ChildPlan(
                label="design-area",
                intent="Lead design",
                assignee=uid("member"),
                execution_mode=ExecutionMode.DELEGATION,
            )
        ],
    )

    assert result.authority_denied == "nested delegation requires an explicit Team grant"
    assert ledger.tasks.children(parent.id) == []
    assert ledger.team_members.get(parent.team_id or "", uid("member")) is None


def test_nested_delegation_without_parent_grant_refuses_whole_wave(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger, can_subdelegate=False)

    result = service.decompose(
        parent_id=parent.id,
        revision="nested-denied-run",
        actor_employee_id="lead",
        children=[
            ChildPlan(
                label="design-area",
                intent="Lead design",
                assignee=uid("member"),
                execution_mode=ExecutionMode.DELEGATION,
            )
        ],
    )

    assert result.authority_denied == "nested delegation is not granted"
    assert ledger.tasks.children(parent.id) == []
    assert len(ledger.teams.list_active()) == 1


def test_team_size_limit_refuses_whole_wave(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger, max_team_size=1)

    result = service.decompose(
        parent_id=parent.id,
        revision="oversize-run",
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.authority_denied == "Team size limit exceeded"
    assert ledger.tasks.children(parent.id) == []


def test_decompose_refuses_self_and_non_report_for_whole_wave(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)

    self_result = service.decompose(
        parent_id=parent.id,
        revision="self-run",
        actor_employee_id="lead",
        children=[ChildPlan(label="self", intent="Self assigned", assignee="lead")],
    )
    non_report_result = service.decompose(
        parent_id=parent.id,
        revision="non-report-run",
        actor_employee_id="lead",
        children=[ChildPlan(label="other", intent="Other", assignee=uid("forger"))],
    )

    assert self_result.unknown_assignees == ("lead",)
    assert non_report_result.unknown_assignees == (uid("forger"),)
    assert ledger.tasks.children(parent.id) == []


def test_nested_delegation_refuses_exhausted_depth(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger, max_depth=0)

    result = service.decompose(
        parent_id=parent.id,
        revision="depth-run",
        actor_employee_id="lead",
        children=[
            ChildPlan(
                label="nested",
                intent="Nested",
                assignee=uid("member"),
                execution_mode=ExecutionMode.DELEGATION,
            )
        ],
    )

    assert result.authority_denied == "delegation depth limit exceeded"
    assert ledger.tasks.children(parent.id) == []


def test_kernel_depth_cap_refusal_commits_no_team_writes(ledger: Ledger) -> None:
    """A DepthCapped refusal from the KERNEL cap (not the authority layer) must not leave the
    wave's Team mutations behind: the tool reports 'nothing was created' and the roster must
    agree. The fail-closed recovery card decompose() opens is still expected to persist."""
    service, parent = _seed_delegation_parent(ledger, max_depth=3)
    assert parent.team_id is not None
    ledger._conn.execute(  # arrange: parent already AT the kernel request-depth ceiling
        "UPDATE task SET request_depth = ? WHERE id = ?",
        (DEFAULT_REQUEST_DEPTH_CAP, parent.id),
    )
    ledger._conn.commit()
    roster_before = {m.employee_id for m in ledger.team_members.members_of(parent.team_id)}
    teams_before = len(ledger.teams.list_active())

    result = service.decompose(
        parent_id=parent.id,
        revision=uid("depth-cap-run"),
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.depth_capped is True
    assert ledger.tasks.children(parent.id) == []
    roster_after = {m.employee_id for m in ledger.team_members.members_of(parent.team_id)}
    assert roster_after == roster_before  # 'member' was NOT silently added to the Team
    assert len(ledger.teams.list_active()) == teams_before
    # decompose()'s fail-closed contract still holds: the operator card survives the refusal
    assert ledger.recovery_actions.active_for_source(parent.id) is not None


def test_reassign_terminal_child_refusal_commits_no_team_writes(ledger: Ledger) -> None:
    """reassign on a terminal child reports 'no assignment changed' — the target employee must
    not be left on the Team roster by a refused call."""
    service, parent = _seed_delegation_parent(ledger)
    assert parent.team_id is not None
    ledger.employees.create(
        Employee(id=uid("member2"), name="Member Two", role="designer", reports_to="lead")
    )
    dec = service.decompose(
        parent_id=parent.id,
        revision=uid("seed-run"),
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )
    child_id = dec.child_ids["design"]
    ledger.tasks.set_status(child_id, TaskStatus.DONE)  # terminal → assign_task will refuse
    _start_integrating(ledger, parent)
    roster_before = {m.employee_id for m in ledger.team_members.members_of(parent.team_id)}

    result = service.reassign(
        parent_id=parent.id, task_id=child_id, assignee=uid("member2"), assigned_by="lead"
    )

    assert result.terminal_or_missing is True and not result.assigned
    roster_after = {m.employee_id for m in ledger.team_members.members_of(parent.team_id)}
    assert roster_after == roster_before  # member2 was NOT silently added


def test_contract_spend_widening_refuses_whole_wave(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(
        ledger,
        profile_spend_limit_cents=10_000,
        contract_spend_limit_cents=20_000,
    )

    result = service.decompose(
        parent_id=parent.id,
        revision="spend-run",
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.authority_denied == "delegation contract exceeds an authority layer"
    assert ledger.tasks.children(parent.id) == []


def test_nested_delegation_retry_is_exact_once(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)
    plan = ChildPlan(
        label="nested",
        intent="Nested",
        assignee=uid("member"),
        execution_mode=ExecutionMode.DELEGATION,
        can_subdelegate=True,
    )

    first = service.decompose(
        parent_id=parent.id,
        revision=uid("retry-run"),
        actor_employee_id="lead",
        children=[plan],
    )
    second = service.decompose(
        parent_id=parent.id,
        revision=uid("retry-run"),
        actor_employee_id="lead",
        children=[plan],
    )

    assert first.child_ids == second.child_ids
    assert len(ledger.tasks.children(parent.id)) == 1
    assert len(ledger.teams.list_active()) == 2
    child_id = first.child_ids["nested"]
    assert ledger.delegation_contracts.get(child_id) is not None


def test_mid_wave_failure_rolls_back_before_clean_retry(
    ledger: Ledger, monkeypatch: pytest.MonkeyPatch
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    original_create_child = ledger.create_child
    calls = 0

    def fail_on_second_child(claim_id: str, child: Task):
        nonlocal calls
        calls += 1
        if calls == 2:
            raise RuntimeError("injected mid-wave crash")
        return original_create_child(claim_id, child)

    monkeypatch.setattr(ledger, "create_child", fail_on_second_child)
    plans = [
        ChildPlan(label="one", intent="One", assignee=uid("member")),
        ChildPlan(label="two", intent="Two", assignee=uid("member")),
    ]
    with pytest.raises(RuntimeError, match="injected mid-wave crash"):
        service.decompose(
            parent_id=parent.id,
            revision=uid("crash-run"),
            actor_employee_id="lead",
            children=plans,
        )

    assert ledger.tasks.children(parent.id) == []
    assert ledger.team_members.get(parent.team_id or "", uid("member")) is None
    monkeypatch.setattr(ledger, "create_child", original_create_child)

    result = service.decompose(
        parent_id=parent.id,
        revision=uid("crash-run"),
        actor_employee_id="lead",
        children=plans,
    )
    assert set(result.child_ids) == {"one", "two"}
    assert len(ledger.tasks.children(parent.id)) == 2


# ---------------------------------------------------------------------------
# Actor-aware authorization shared across decompose / submit_one / reassign
# ---------------------------------------------------------------------------


def test_decompose_rejects_reviewer_assignee_without_side_effects(ledger: Ledger) -> None:
    """_reviewer_assignees gate: a reviewer employee cannot own deliverable work (decompose path)."""
    service, parent = _seed_delegation_parent(ledger)
    ledger.employees.create(
        Employee(id=uid("rev"), name="Reviewer", role="reviewer", reports_to="lead")
    )

    result = service.decompose(
        parent_id=parent.id,
        revision="rev-run",
        actor_employee_id="lead",
        children=[ChildPlan(label="audit", intent="Audit release", assignee=uid("rev"))],
    )

    assert result.reviewer_assignees == (uid("rev"),)
    assert result.child_ids == {}
    assert ledger.tasks.children(parent.id) == []


def test_decompose_rejects_none_actor_in_delegation_mode(ledger: Ledger) -> None:
    """_authorize_wave: None actor_employee_id fails closed."""
    service, parent = _seed_delegation_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision="none-actor-run",
        actor_employee_id=None,
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )

    assert result.authority_denied == "actor is not the delegation contract lead"
    assert ledger.tasks.children(parent.id) == []


def test_decompose_rejects_delegation_child_without_assignee(ledger: Ledger) -> None:
    """_authorize_wave: a DELEGATION child with assignee=None is refused (no lead)."""
    service, parent = _seed_delegation_parent(ledger)

    result = service.decompose(
        parent_id=parent.id,
        revision="no-lead-run",
        actor_employee_id="lead",
        children=[
            ChildPlan(
                label="unled-area",
                intent="Lead something",
                assignee=None,
                execution_mode=ExecutionMode.DELEGATION,
            )
        ],
    )

    assert result.authority_denied == "delegation child requires a lead"
    assert ledger.tasks.children(parent.id) == []


# --- submit_one shares _reviewer_assignees and _unknown_assignees ---


def test_submit_one_rejects_reviewer_assignee(ledger: Ledger) -> None:
    """_reviewer_assignees gate: same reviewer rejection via submit_one path."""
    service, parent = _seed_delegation_parent(ledger)
    _start_integrating(ledger, parent)
    ledger.employees.create(
        Employee(id=uid("rev"), name="Reviewer", role="reviewer", reports_to="lead")
    )

    result = service.submit_one(
        parent_id=parent.id,
        revision="sub-rev-run",
        child=ChildPlan(label="audit", intent="Audit release", assignee=uid("rev")),
    )

    assert result.reviewer_assignees == (uid("rev"),)
    assert result.child_id is None
    assert ledger.tasks.children(parent.id) == []


def test_submit_one_rejects_unknown_assignee(ledger: Ledger) -> None:
    """_unknown_assignees gate: non-direct-report via submit_one path."""
    service, parent = _seed_delegation_parent(ledger)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision="sub-unk-run",
        child=ChildPlan(label="rogue", intent="Rogue work", assignee=uid("forger")),
    )

    assert result.unknown_assignees == (uid("forger"),)
    assert result.child_id is None
    assert ledger.tasks.children(parent.id) == []


def test_submit_one_creates_gated_child(ledger: Ledger) -> None:
    """submit_one happy path: valid direct-report child is created and assigned."""
    service, parent = _seed_delegation_parent(ledger)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision=uid("sub-ok-run"),
        actor_employee_id="lead",
        child=ChildPlan(label="design", intent="Design widget", assignee=uid("member")),
    )

    assert result.child_id is not None
    child = ledger.tasks.get(result.child_id)
    assert child is not None
    assert child.assignee_employee_id == uid("member")
    assert child.parent_id == parent.id
    assert child.execution_mode is ExecutionMode.DELIVERY
    assert ledger.team_members.get(parent.team_id or "", uid("member")) is not None


def test_submit_one_atomically_replaces_one_rejected_required_child(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    rejected = service.decompose(
        parent_id=parent.id,
        revision=uid("initial-wave"),
        actor_employee_id="lead",
        children=[ChildPlan(label="broken", intent="Broken", assignee=uid("member"))],
    ).child_ids["broken"]
    ledger.tasks.set_status(rejected, TaskStatus.REJECTED)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision=uid("correction-wave"),
        actor_employee_id="lead",
        child=ChildPlan(
            label="fixed",
            intent="Replace the broken result",
            assignee=uid("member"),
            replaces_task_id=rejected,
        ),
    )

    assert result.child_id is not None
    assert ledger.dependencies.blockers(parent.id) == [result.child_id]
    assert ledger.tasks.get(rejected).status is TaskStatus.REJECTED  # type: ignore[union-attr]


def test_submit_one_respects_contract_direct_child_record_cap(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger, max_direct_children=2)
    initial = service.decompose(
        parent_id=parent.id,
        revision=uid("initial-wave"),
        actor_employee_id="lead",
        children=[
            ChildPlan(label="first", intent="First", assignee=uid("member")),
            ChildPlan(label="second", intent="Second", assignee=uid("member")),
        ],
    ).child_ids
    rejected = initial["first"]
    ledger.tasks.set_status(rejected, TaskStatus.REJECTED)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision=uid("correction-wave"),
        actor_employee_id="lead",
        child=ChildPlan(
            label="replacement",
            intent="Replace first",
            assignee=uid("member"),
            replaces_task_id=rejected,
        ),
    )

    assert result.child_id is None
    assert result.authority_denied == "delegation contract direct child limit exceeded"
    assert {child.id for child in ledger.tasks.children(parent.id)} == set(initial.values())
    assert set(ledger.dependencies.blockers(parent.id)) == set(initial.values())


def test_submit_one_requires_replacement_lineage_while_a_direct_child_failed(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    rejected = service.decompose(
        parent_id=parent.id,
        revision=uid("initial-wave"),
        actor_employee_id="lead",
        children=[ChildPlan(label="broken", intent="Broken", assignee=uid("member"))],
    ).child_ids["broken"]
    ledger.tasks.set_status(rejected, TaskStatus.REJECTED)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision=uid("correction-wave"),
        actor_employee_id="lead",
        child=ChildPlan(label="duplicate", intent="Redo the work", assignee=uid("member")),
    )

    assert result.child_id is None
    assert result.authority_denied is not None
    assert result.authority_denied.startswith(
        f"failed direct child {rejected} must be named in replaces_task_id"
    )
    # The refusal teaches the exact corrective call (live T3: the lead exhausted its
    # integrate budget re-sending the same refused submit without this).
    assert f'replaces_task_id="{rejected}"' in result.authority_denied
    assert [child.id for child in ledger.tasks.children(parent.id)] == [rejected]


def test_submit_one_refuses_label_collision_with_guidance(ledger: Ledger) -> None:
    """Live T3: corrective submit reusing the failed child's label hit a raw duplicate-key
    error (child ids derive from (parent, label)). Refuse typed, with the fix named."""
    service, parent = _seed_delegation_parent(ledger)
    rejected = service.decompose(
        parent_id=parent.id,
        revision=uid("initial-wave"),
        actor_employee_id="lead",
        children=[ChildPlan(label="links", intent="Build links", assignee=uid("member"))],
    ).child_ids["links"]
    ledger.tasks.set_status(rejected, TaskStatus.REJECTED)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision=uid("correction-wave"),
        actor_employee_id="lead",
        child=ChildPlan(
            label="links",  # the collision: same label as the failed child
            intent="Redo links",
            assignee=uid("member"),
            replaces_task_id=rejected,
        ),
    )

    assert result.child_id is None
    assert result.authority_denied is not None
    assert "pick a NEW label" in result.authority_denied
    assert [child.id for child in ledger.tasks.children(parent.id)] == [rejected]


def test_submit_one_refuses_a_different_second_follow_up_in_the_same_beat(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    _start_integrating(ledger, parent)

    first = service.submit_one(
        parent_id=parent.id,
        revision=uid("one-integrate-beat"),
        actor_employee_id="lead",
        child=ChildPlan(label="first", intent="First gap", assignee=uid("member")),
    )
    second = service.submit_one(
        parent_id=parent.id,
        revision=uid("one-integrate-beat"),
        actor_employee_id="lead",
        child=ChildPlan(label="second", intent="Second gap", assignee=uid("member")),
    )

    assert first.child_id is not None
    assert second.child_id is None
    assert second.authority_denied == "this manager beat already committed a different child wave"
    assert [child.id for child in ledger.tasks.children(parent.id)] == [first.child_id]


def test_submit_one_rejects_forged_actor_without_partial_writes(ledger: Ledger) -> None:
    service, parent = _seed_delegation_parent(ledger)
    _start_integrating(ledger, parent)

    result = service.submit_one(
        parent_id=parent.id,
        revision="sub-forged-run",
        actor_employee_id=uid("forger"),
        child=ChildPlan(label="design", intent="Design widget", assignee=uid("member")),
    )

    assert result.authority_denied == "actor is not the delegation contract lead"
    assert ledger.tasks.children(parent.id) == []
    assert ledger.team_members.get(parent.team_id or "", uid("member")) is None


# --- reassign shares _is_direct_report ---


def test_reassign_rejects_non_direct_report(ledger: Ledger) -> None:
    """_is_direct_report gate: reassign refuses an employee not reporting to the parent's assignee."""
    service, parent = _seed_delegation_parent(ledger)
    # Create a child to reassign
    dec = service.decompose(
        parent_id=parent.id,
        revision=uid("seed-run"),
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )
    child_id = dec.child_ids["design"]
    _start_integrating(ledger, parent)

    result = service.reassign(
        parent_id=parent.id, task_id=child_id, assignee=uid("forger"), assigned_by="lead"
    )

    assert result.unknown_assignee == uid("forger")
    assert not result.assigned
    # Original assignment unchanged
    assert ledger.tasks.get(child_id) is not None
    assert ledger.tasks.get(child_id).assignee_employee_id == uid("member")  # type: ignore[union-attr]


def test_reassign_rejects_non_child_task(ledger: Ledger) -> None:
    """reassign refuses a task whose parent_id does not match the claimed parent."""
    service, parent = _seed_delegation_parent(ledger)
    # An unrelated task not parented under parent
    orphan = Task(
        id=uid("task-orphan"),
        intent="Orphan work",
        status=TaskStatus.TODO,
        goal_id=uid("goal-release"),
    )
    ledger.tasks.submit(orphan)
    _start_integrating(ledger, parent)

    result = service.reassign(
        parent_id=parent.id, task_id=uid("task-orphan"), assignee=uid("member"), assigned_by="lead"
    )

    assert result.not_child is True
    assert not result.assigned


def test_reassign_returns_terminal_or_missing_for_unknown_task(ledger: Ledger) -> None:
    """reassign fails closed when the target task does not exist."""
    service, parent = _seed_delegation_parent(ledger)
    _start_integrating(ledger, parent)

    result = service.reassign(
        parent_id=parent.id, task_id=uid("task-ghost"), assignee=uid("member"), assigned_by="lead"
    )

    assert result.terminal_or_missing is True
    assert not result.assigned


def test_reassign_succeeds_for_direct_report_child(ledger: Ledger) -> None:
    """reassign happy path: re-routes a child task to another direct report."""
    service, parent = _seed_delegation_parent(ledger)
    ledger.employees.create(
        Employee(id=uid("member2"), name="Member2", role="designer", reports_to="lead")
    )
    dec = service.decompose(
        parent_id=parent.id,
        revision=uid("seed2-run"),
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )
    child_id = dec.child_ids["design"]
    _start_integrating(ledger, parent)

    result = service.reassign(
        parent_id=parent.id, task_id=child_id, assignee=uid("member2"), assigned_by="lead"
    )

    assert result.assigned is True
    child = ledger.tasks.get(child_id)
    assert child is not None and child.assignee_employee_id == uid("member2")
    assert ledger.team_members.get(parent.team_id or "", uid("member2")) is not None


def test_reassign_rejects_forged_actor_without_changing_assignment(
    ledger: Ledger,
) -> None:
    service, parent = _seed_delegation_parent(ledger)
    ledger.employees.create(
        Employee(id=uid("member2"), name="Member2", role="designer", reports_to="lead")
    )
    dec = service.decompose(
        parent_id=parent.id,
        revision=uid("reassign-seed-run"),
        actor_employee_id="lead",
        children=[ChildPlan(label="design", intent="Design", assignee=uid("member"))],
    )
    child_id = dec.child_ids["design"]
    _start_integrating(ledger, parent)

    result = service.reassign(
        parent_id=parent.id,
        task_id=child_id,
        assignee=uid("member2"),
        assigned_by=uid("forger"),
    )

    assert result.authority_denied == "actor is not the delegation contract lead"
    child = ledger.tasks.get(child_id)
    assert child is not None and child.assignee_employee_id == uid("member")
    assert ledger.team_members.get(parent.team_id or "", uid("member2")) is None
