# Generated by AI (UnitTest MCP)
"""Decomposition — exact-once manager fan-out (spec 02 §4).

``decompose`` is the orchestration over spec 01's durable ``decomposition_claim`` +
``create_child`` primitives: open-or-resume a claim keyed on
``(source_task_id, accepted_plan_revision_id)``, create each child one-per-transaction
(``parent_id`` set, goal inherited, ``request_depth`` bumped), wire a *gating* child as a
first-class ``task_dependency`` of the parent, then seal the claim. A run that dies
mid-fan-out resumes from the same fingerprint and reuses the partial result — never
restarts, never double-fans-out.
"""

from __future__ import annotations

import pytest

from chorus.ledger import Ledger, Task, TaskStatus
from chorus.ledger._models import (
    ActivityVerb,
    Artifact,
    ArtifactRevision,
    ArtifactType,
    DecompositionStatus,
    DodStatus,
    Goal,
    OriginKind,
    WakeReason,
)
from chorus.lifecycle import ChildSpec, Fanned, decompose
from chorus.testing import uid
from chorus.workforce import Employee

REV = uid(
    "rev_1"
)  # the accepted-plan-revision id, backed by a real artifact revision on the source


@pytest.fixture
def emp(ledger: Ledger) -> Employee:
    return ledger.employees.create(Employee(id="emp_1", name="alice", role="engineer"))


@pytest.fixture
def goal(ledger: Ledger) -> Goal:
    return ledger.goals.create(Goal(id=uid("g1"), title="ship the thing"))


@pytest.fixture
def source(ledger: Ledger, emp: Employee, goal: Goal) -> Task:
    """The task being split, plus its accepted plan revision (``REV``) for the claim FK."""
    task = ledger.tasks.submit(
        Task(
            id=uid("src"),
            intent="big thing",
            status=TaskStatus.IN_PROGRESS,
            assignee_employee_id="emp_1",
            goal_id=uid("g1"),
            depth=1,
            request_depth=2,
        )
    )
    ledger.artifacts.create(Artifact(id=uid("art_src"), task_id=uid("src"), type=ArtifactType.DOC))
    ledger.artifact_revisions.record(
        ArtifactRevision(id=REV, artifact_id=uid("art_src"), resource_ref={"plan": "v1"})
    )
    return task


def _child(task_id: str) -> Task:
    return Task(
        id=task_id,
        intent=f"part {task_id}",
        status=TaskStatus.TODO,
        assignee_employee_id="emp_1",
        origin_kind=OriginKind.DECOMPOSITION,
    )


def test_decompose_creates_children_with_inherited_structure(ledger: Ledger, source: Task) -> None:
    decompose(
        ledger,
        source_task_id=source.id,
        accepted_plan_revision_id=REV,
        children=[ChildSpec(_child(uid("c1"))), ChildSpec(_child(uid("c2")))],
    )
    c1 = ledger.tasks.get(uid("c1"))
    c2 = ledger.tasks.get(uid("c2"))
    assert c1 is not None and c2 is not None
    for child in (c1, c2):
        assert child.parent_id == uid("src")  # structure
        assert child.goal_id == uid("g1")  # inherited goal
        assert child.request_depth == 3  # bumped from source's 2
        assert child.depth == 2  # bumped from source's 1


def test_gating_child_becomes_a_first_class_dependency(ledger: Ledger, source: Task) -> None:
    decompose(
        ledger,
        source_task_id=source.id,
        accepted_plan_revision_id=REV,
        children=[ChildSpec(_child(uid("c1")), gates_parent=True), ChildSpec(_child(uid("c2")))],
    )
    # parent-waits-on-child is a blocker, not parent_id (spec 02 §4.3).
    assert ledger.dependencies.blockers(uid("src")) == [uid("c1")]
    assert ledger.dependencies.unresolved_blockers(uid("src")) == [uid("c1")]


def test_claim_completes_after_fan_out(ledger: Ledger, source: Task) -> None:
    outcome = decompose(
        ledger,
        source_task_id=source.id,
        accepted_plan_revision_id=REV,
        children=[ChildSpec(_child(uid("c1"))), ChildSpec(_child(uid("c2")))],
    )
    assert isinstance(outcome, Fanned)
    assert outcome.claim.status is DecompositionStatus.COMPLETED
    assert outcome.claim.child_task_ids == [uid("c1"), uid("c2")]


def test_resume_reuses_partial_result_no_duplicate_children(ledger: Ledger, source: Task) -> None:
    specs = [ChildSpec(_child(uid("c1")), gates_parent=True), ChildSpec(_child(uid("c2")))]
    first = decompose(
        ledger, source_task_id=source.id, accepted_plan_revision_id=REV, children=specs
    )
    # A retry against the SAME accepted plan revision resumes the same claim, no double fan-out.
    second = decompose(
        ledger, source_task_id=source.id, accepted_plan_revision_id=REV, children=specs
    )
    assert isinstance(first, Fanned) and isinstance(second, Fanned)
    assert second.claim.id == first.claim.id  # exact-once: one claim per (source, revision)
    assert second.claim.child_task_ids == [uid("c1"), uid("c2")]  # not duplicated
    assert ledger.dependencies.blockers(uid("src")) == [uid("c1")]  # dependency add is idempotent


def test_unknown_source_raises(ledger: Ledger, source: Task) -> None:
    with pytest.raises(KeyError):
        decompose(
            ledger,
            source_task_id=uid("nope"),
            accepted_plan_revision_id=REV,
            children=[ChildSpec(_child(uid("c1")))],
        )


def test_completing_gating_children_fires_children_done_to_parent(
    ledger: Ledger, source: Task
) -> None:
    # End-to-end wiring: decompose sets parent_id so finalize_beat's last-child rollup fires.
    decompose(
        ledger,
        source_task_id=source.id,
        accepted_plan_revision_id=REV,
        children=[ChildSpec(_child(uid("c1"))), ChildSpec(_child(uid("c2")))],
    )
    ledger.finalize_beat(task_id=uid("c1"), run_id=uid("r1"), dod_status=DodStatus.PASSED)
    fired = ledger.finalize_beat(task_id=uid("c2"), run_id=uid("r2"), dod_status=DodStatus.PASSED)
    reasons = {w.reason for w in fired}
    assert WakeReason.CHILDREN_DONE in reasons
    parent_wakes = [w for w in fired if w.payload.get("task_id") == uid("src")]
    assert parent_wakes  # the parent's assignee is woken


# ---------------------------------------------------------------------------
# File-backed SQLite restart safety (spec 02 §4.2)
# ---------------------------------------------------------------------------


def _seed_source(ledger: Ledger) -> Task:
    """Insert the employee, goal, source task, and plan revision needed by ``decompose``."""
    ledger.employees.create(Employee(id="emp_1", name="alice", role="engineer"))
    ledger.goals.create(Goal(id=uid("g1"), title="ship the thing"))
    task = ledger.tasks.submit(
        Task(
            id=uid("src"),
            intent="big thing",
            status=TaskStatus.IN_PROGRESS,
            assignee_employee_id="emp_1",
            goal_id=uid("g1"),
            depth=1,
            request_depth=2,
        )
    )
    ledger.artifacts.create(Artifact(id=uid("art_src"), task_id=uid("src"), type=ArtifactType.DOC))
    ledger.artifact_revisions.record(
        ArtifactRevision(id=REV, artifact_id=uid("art_src"), resource_ref={"plan": "v1"})
    )
    return task


def test_restart_after_claim_open_failure_resumes_fan_out(
    pg_database: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    db = pg_database
    company = uid("resume-co")
    specs = [ChildSpec(_child(uid("c1")), gates_parent=True), ChildSpec(_child(uid("c2")))]

    lg1 = Ledger.open(db, company_id=company)
    _seed_source(lg1)
    monkeypatch.setattr(
        lg1, "create_child", lambda *_args: (_ for _ in ()).throw(RuntimeError("crash"))
    )
    with pytest.raises(RuntimeError, match="crash"):
        decompose(
            lg1,
            source_task_id=uid("src"),
            accepted_plan_revision_id=REV,
            children=specs,
        )
    claim = lg1.decomposition_claims.by_source_revision(uid("src"), REV)
    assert claim is not None
    assert claim.status is DecompositionStatus.IN_FLIGHT
    assert claim.child_task_ids == []
    claim_id = claim.id
    lg1.close()
    monkeypatch.undo()

    lg2 = Ledger.open(db, company_id=company)
    outcome = decompose(
        lg2,
        source_task_id=uid("src"),
        accepted_plan_revision_id=REV,
        children=specs,
    )
    assert isinstance(outcome, Fanned)
    assert outcome.claim.id == claim_id
    assert outcome.claim.status is DecompositionStatus.COMPLETED
    assert outcome.claim.child_task_ids == [uid("c1"), uid("c2")]
    assert [task.id for task in lg2.tasks.all() if task.parent_id == uid("src")] == [
        uid("c1"),
        uid("c2"),
    ]
    assert lg2.dependencies.blockers(uid("src")) == [uid("c1")]
    assert [event.verb for event in lg2.activity.by_subject("task", uid("src"))] == [
        ActivityVerb.DECOMPOSED
    ]
    lg2.close()


def test_restart_after_first_child_persisted_before_dependency(
    pg_database: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    db = pg_database
    company = uid("resume-co-2")
    specs = [ChildSpec(_child(uid("c1")), gates_parent=True), ChildSpec(_child(uid("c2")))]

    lg1 = Ledger.open(db, company_id=company)
    _seed_source(lg1)
    original_create_child = lg1.create_child

    def persist_then_crash(claim_id: str, child: Task) -> object:
        original_create_child(claim_id, child)
        raise RuntimeError("crash before dependency")

    monkeypatch.setattr(lg1, "create_child", persist_then_crash)
    with pytest.raises(RuntimeError, match="crash before dependency"):
        decompose(
            lg1,
            source_task_id=uid("src"),
            accepted_plan_revision_id=REV,
            children=specs,
        )
    claim = lg1.decomposition_claims.by_source_revision(uid("src"), REV)
    assert claim is not None
    assert claim.child_task_ids == [uid("c1")]
    assert lg1.dependencies.blockers(uid("src")) == []
    claim_id = claim.id
    lg1.close()
    monkeypatch.undo()

    lg2 = Ledger.open(db, company_id=company)
    outcome = decompose(
        lg2,
        source_task_id=uid("src"),
        accepted_plan_revision_id=REV,
        children=specs,
    )
    assert isinstance(outcome, Fanned)
    assert outcome.claim.id == claim_id
    assert outcome.claim.status is DecompositionStatus.COMPLETED
    assert outcome.claim.child_task_ids == [uid("c1"), uid("c2")]
    assert [task.id for task in lg2.tasks.all() if task.parent_id == uid("src")] == [
        uid("c1"),
        uid("c2"),
    ]
    assert lg2.dependencies.blockers(uid("src")) == [uid("c1")]
    assert [event.verb for event in lg2.activity.by_subject("task", uid("src"))] == [
        ActivityVerb.DECOMPOSED
    ]
    lg2.close()
