# Generated by AI (UnitTest MCP)
"""The scheduler consumes one complete task-aware execution profile."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

import pytest

from chorus.heartbeat import Scheduler, Wake, WakeReason
from chorus.heartbeat._beat import BeatOutcome
from chorus.ledger import (
    ActivityVerb,
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    ManagementProfile,
    SqliteLedger,
    Task,
    TaskStatus,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
    WakeStatus,
)
from chorus.memory import SprintDelta
from chorus.outcomes import Artifact, ArtifactType, LanderRegistry
from chorus.roles import RoleRegistry, default_roles
from chorus.workforce import Employee, LedgerWorkforce

pytestmark = pytest.mark.integration

_NOW = datetime(2026, 6, 17, 12, tzinfo=UTC)
_RUBRIC = "integrate every release outcome and independently verify the assembled result"


class _RecordingBeat:
    def __init__(self, *, passed: bool = True, review_passed: bool | None = None) -> None:
        self.rubrics: list[str] = []
        self.passed = passed
        self.review_passed = review_passed
        self.intents: list[str] = []

    async def run_task(
        self,
        *,
        task_id: str,
        intent: str,
        verification: object = (),
        rubric: str = "",
        observer: object = None,
        run_id: str | None = None,
    ) -> BeatOutcome:
        self.rubrics.append(rubric)
        self.intents.append(intent)
        passed = (
            self.review_passed
            if intent.startswith("Independently verify") and self.review_passed is not None
            else self.passed
        )
        return BeatOutcome(
            passed=passed,
            outcome={},
            summary="release subtree integrated" if passed else "objective verification failed",
        )


class _RecordingMemory:
    def __init__(self) -> None:
        self.appended: list[SprintDelta] = []

    def append(self, delta: SprintDelta) -> None:
        self.appended.append(delta)


class _SubtreeLander:
    outcome_kind = "subtree"

    def __init__(self) -> None:
        self.landed: list[str] = []

    async def land(self, task: Any, result: Any) -> Artifact:
        self.landed.append(task.id)
        return Artifact(
            task_id=task.id,
            type=ArtifactType.ARTIFACT,
            resource_ref={"kind": "subtree"},
        )


def _seed_delegation(
    ledger: SqliteLedger, *, child_status: TaskStatus = TaskStatus.DONE
) -> Employee:
    lead = ledger.employees.create(Employee(id="lead", name="Lead", role="backend_engineer"))
    worker = ledger.employees.create(
        Employee(id="worker", name="Worker", role="backend_engineer", reports_to=lead.id)
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=2,
            allowed_professions=("backend_engineer",),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id="team-release",
            name="Release",
            lead_employee_id=lead.id,
            created_by="user-admin",
            status=TeamStatus.ACTIVE,
        )
    )
    for employee_id, membership_role in (
        (lead.id, TeamMembershipRole.LEAD),
        (worker.id, TeamMembershipRole.MEMBER),
    ):
        ledger.team_members.add(
            TeamMember(
                team_id="team-release",
                employee_id=employee_id,
                source_manager_id=lead.id,
                membership_role=membership_role,
            )
        )
    ledger.tasks.submit(
        Task(
            id="task-release",
            intent="coordinate the release",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id="team-release",
            assignee_employee_id=lead.id,
        )
    )
    ledger.tasks.submit(
        Task(
            id="task-child",
            parent_id="task-release",
            intent="implement the release endpoint",
            status=child_status,
            assignee_employee_id=worker.id,
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id="task-release",
            team_id="team-release",
            lead_employee_id=lead.id,
            management_profile_version=1,
            max_depth=1,
            max_team_size=2,
            objective_rubric=_RUBRIC,
            status=DelegationContractStatus.INTEGRATING,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id="wake-release",
            employee_id=lead.id,
            reason=WakeReason.CHILDREN_DONE,
            payload={"task_id": "task-release"},
        )
    )
    return lead


async def test_delegation_profile_drives_scheduler_contract(ledger: SqliteLedger) -> None:
    lead = _seed_delegation(ledger)
    beat = _RecordingBeat()
    memory = _RecordingMemory()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=memory,
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    verifier = ledger.dod.verifier_for_task("task-release")
    assert verifier is not None
    assert (verifier.rubric(), verifier.artifact_class) == (_RUBRIC, "subtree")
    assert beat.rubrics == [_RUBRIC, _RUBRIC]
    assert beat.intents[1].startswith("Independently verify")
    assert len(memory.appended) == 1 and memory.appended[0].scope == "team"
    assert lander.landed == ["task-release"]
    assert ledger.tasks.get("task-release").status is TaskStatus.DONE  # type: ignore[union-attr]
    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None
    assert contract.status is DelegationContractStatus.DONE
    assert contract.accepted_run_id is not None and contract.accepted_at is not None
    team = ledger.teams.get("team-release")
    assert team is not None and team.status is TeamStatus.ARCHIVED
    contract_events = ledger.activity.by_subject("delegation_contract", "task-release")
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload["passed"] is True
    assert contract_events[-1].payload["reviewer_id"] == "system-verifier"
    verification_run = ledger.runs.get(str(contract_events[-1].payload["verification_run_id"]))
    assert verification_run is not None and verification_run.principal_kind == "system"
    verification_runs = [
        run for run in ledger.runs.for_task("task-release") if run.principal_id == "system-verifier"
    ]
    assert len(verification_runs) == 1
    assert verification_runs[0].employee_id == lead.id
    assert lead.role == "backend_engineer"


async def test_failed_parent_verification_returns_contract_to_integrating(
    ledger: SqliteLedger,
) -> None:
    _seed_delegation(ledger)
    beat = _RecordingBeat(review_passed=False)
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None
    assert contract.status is DelegationContractStatus.INTEGRATING
    assert contract.accepted_run_id is not None and contract.accepted_at is not None
    assert ledger.tasks.get("task-release").status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert ledger.teams.get("team-release").status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert lander.landed == []
    queued = ledger.wakes.queued(employee_id="lead")
    assert len(queued) == 1
    assert queued[0].reason is WakeReason.CHILDREN_DONE
    contract_events = ledger.activity.by_subject("delegation_contract", "task-release")
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload["passed"] is False
    assert contract_events[-1].payload["reviewer_id"] == "system-verifier"


async def test_rejected_required_child_cannot_reach_acceptance_or_verification(
    ledger: SqliteLedger,
) -> None:
    _seed_delegation(ledger, child_status=TaskStatus.REJECTED)
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None and contract.status is DelegationContractStatus.INTEGRATING
    assert contract.accepted_run_id is None
    assert ledger.tasks.get("task-release").status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert not any(intent.startswith("Independently verify") for intent in beat.intents)
    assert ledger.activity.by_subject("delegation_contract", "task-release") == []


async def test_authority_denial_is_never_laundered_into_delegated_success(
    ledger: SqliteLedger,
) -> None:
    """A profile denial refuses the beat BEFORE it runs — on a parent WITH children that must
    surface as a FAILED run + recovery, never as the 'success by delegating' branch (which would
    record SUCCEEDED and walk the denial into lead acceptance)."""
    _seed_delegation(ledger)
    ledger.teams.archive("team-release")  # revoked mid-flight → ExecutionProfileDenied
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    assert beat.rubrics == []  # the denied beat never reached the runner
    runs = ledger.runs.for_task("task-release")
    assert [run.status.value for run in runs] == ["failed"]
    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None and contract.accepted_run_id is None
    assert ledger.activity.by_subject("delegation_contract", "task-release") == []
    assert ledger.recovery_actions.active_for_source("task-release") is not None


async def test_unmigrated_manager_is_blocked_before_dispatch(
    ledger: SqliteLedger, caplog: pytest.LogCaptureFixture
) -> None:
    manager = ledger.employees.create(
        Employee(id="legacy-manager", name="Legacy Manager", role="manager")
    )
    ledger.tasks.submit(
        Task(
            id="legacy-task",
            intent="ambiguous manager work",
            status=TaskStatus.TODO,
            assignee_employee_id=manager.id,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id="wake-legacy",
            employee_id=manager.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": "legacy-task"},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    with caplog.at_level(logging.WARNING, logger="chorus.heartbeat.scheduler"):
        report = await scheduler.tick(_NOW)
        await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    assert ledger.wakes.queued() == []
    assert ledger.tasks.get("legacy-task").status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source("legacy-task")
    assert recovery is not None and recovery.cause == "unmigrated_manager"
    assert recovery.owner_user_id == "operator"
    assert "legacy-manager" in caplog.text and "specialize-manager" in caplog.text


async def test_delegation_integrate_cap_escalates_without_force_acceptance(
    ledger: SqliteLedger,
) -> None:
    _seed_delegation(ledger)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    assert contract.accepted_run_id is None
    assert ledger.tasks.get("task-release").status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert ledger.teams.get("team-release").status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source("task-release")
    assert recovery is not None
    assert recovery.owner_employee_id == "lead"
    assert recovery.cause == "integrate_iteration_exhausted"
    assert recovery.evidence == {"iteration": 1, "cap": 0, "contract_task_id": "task-release"}
    assert beat.rubrics == []
    assert lander.landed == []


async def test_restart_closes_landed_delegation_exactly_once(
    ledger: SqliteLedger,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_delegation(ledger)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    crashed_scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )
    land_passed = crashed_scheduler._land_passed

    async def crash_after_landing(*args: Any, **kwargs: Any) -> None:
        await land_passed(*args, **kwargs)
        raise RuntimeError("injected crash after delegation landing")

    monkeypatch.setattr(crashed_scheduler, "_land_passed", crash_after_landing)

    await crashed_scheduler.tick(_NOW)
    with pytest.raises(RuntimeError, match="injected crash"):
        await crashed_scheduler.drain()

    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None and contract.status is DelegationContractStatus.VERIFYING
    assert ledger.tasks.get("task-release").status is TaskStatus.DONE  # type: ignore[union-attr]
    assert ledger.teams.get("team-release").status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert ledger.wakes.get("wake-release").status is WakeStatus.CLAIMED  # type: ignore[union-attr]

    restarted_scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )
    report = await restarted_scheduler.tick(_NOW)
    await restarted_scheduler.drain()

    assert report.recovered == 1
    assert lander.landed == ["task-release"]
    contract = ledger.delegation_contracts.get("task-release")
    assert contract is not None and contract.status is DelegationContractStatus.DONE
    assert ledger.teams.get("team-release").status is TeamStatus.ARCHIVED  # type: ignore[union-attr]
    assert ledger.wakes.get("wake-release").status is WakeStatus.DONE  # type: ignore[union-attr]
    contract_events = ledger.activity.by_subject("delegation_contract", "task-release")
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload == {
        "passed": True,
        "recovered": True,
        "run_id": contract.accepted_run_id,
    }
