# Generated by AI (UnitTest MCP)
"""The scheduler consumes one complete task-aware execution profile."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

import pytest

from chorus.heartbeat import Scheduler, Wake, WakeReason
from chorus.heartbeat._beat import BeatOutcome
from chorus.ledger import (
    ActivityVerb,
    DelegationContract,
    DelegationContractStatus,
    ExecutionMode,
    Ledger,
    ManagementProfile,
    Task,
    TaskStatus,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
    WakeStatus,
)
from chorus.memory import SprintDelta
from chorus.outcomes import Artifact, ArtifactType, LanderRegistry
from chorus.roles import RoleRegistry, default_roles
from chorus.testing import uid
from chorus.workforce import Employee, LedgerWorkforce

pytestmark = pytest.mark.integration

_NOW = datetime(2026, 6, 17, 12, tzinfo=UTC)
_RUBRIC = "integrate every release outcome and independently verify the assembled result"


class _RecordingBeat:
    def __init__(self, *, passed: bool = True, review_passed: bool | None = None) -> None:
        self.rubrics: list[str] = []
        self.passed = passed
        self.review_passed = review_passed
        self.intents: list[str] = []

    async def run_task(
        self,
        *,
        task_id: str,
        intent: str,
        verification: object = (),
        rubric: str = "",
        observer: object = None,
        run_id: str | None = None,
    ) -> BeatOutcome:
        self.rubrics.append(rubric)
        self.intents.append(intent)
        passed = (
            self.review_passed
            if intent.startswith("Independently verify") and self.review_passed is not None
            else self.passed
        )
        return BeatOutcome(
            passed=passed,
            outcome={},
            summary="release subtree integrated" if passed else "objective verification failed",
        )


class _RecordingMemory:
    def __init__(self) -> None:
        self.appended: list[SprintDelta] = []

    def append(self, delta: SprintDelta) -> None:
        self.appended.append(delta)


class _SubtreeLander:
    outcome_kind = "subtree"

    def __init__(self) -> None:
        self.landed: list[str] = []

    async def land(self, task: Any, result: Any) -> Artifact:
        self.landed.append(task.id)
        return Artifact(
            task_id=task.id,
            type=ArtifactType.ARTIFACT,
            resource_ref={"kind": "subtree"},
        )


def _seed_delegation(ledger: Ledger, *, child_status: TaskStatus = TaskStatus.DONE) -> Employee:
    lead = ledger.employees.create(Employee(id="lead", name="Lead", role="backend_engineer"))
    worker = ledger.employees.create(
        Employee(id="worker", name="Worker", role="backend_engineer", reports_to=lead.id)
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=2,
            allowed_professions=("backend_engineer",),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id=uid("team-release"),
            name="Release",
            lead_employee_id=lead.id,
            created_by="user-admin",
            status=TeamStatus.ACTIVE,
        )
    )
    for employee_id, membership_role in (
        (lead.id, TeamMembershipRole.LEAD),
        (worker.id, TeamMembershipRole.MEMBER),
    ):
        ledger.team_members.add(
            TeamMember(
                team_id=uid("team-release"),
                employee_id=employee_id,
                source_manager_id=lead.id,
                membership_role=membership_role,
            )
        )
    ledger.tasks.submit(
        Task(
            id=uid("task-release"),
            intent="coordinate the release",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("team-release"),
            assignee_employee_id=lead.id,
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("task-child"),
            parent_id=uid("task-release"),
            intent="implement the release endpoint",
            status=child_status,
            assignee_employee_id=worker.id,
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("task-release"),
            team_id=uid("team-release"),
            lead_employee_id=lead.id,
            management_profile_version=1,
            max_depth=1,
            max_team_size=2,
            objective_rubric=_RUBRIC,
            status=DelegationContractStatus.INTEGRATING,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-release"),
            employee_id=lead.id,
            reason=WakeReason.CHILDREN_DONE,
            payload={"task_id": uid("task-release")},
        )
    )
    return lead


async def test_delegation_profile_drives_scheduler_contract(ledger: Ledger) -> None:
    lead = _seed_delegation(ledger)
    beat = _RecordingBeat()
    memory = _RecordingMemory()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=memory,
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    verifier = ledger.dod.verifier_for_task(uid("task-release"))
    assert verifier is not None
    assert (verifier.rubric(), verifier.artifact_class) == (_RUBRIC, "subtree")
    # Operator decision (2026-07-18): employees verify their own work — the lead's single integrate
    # beat is the only run; no "Independently verify" system-verifier beat follows it.
    assert beat.rubrics == [_RUBRIC]
    assert not any(intent.startswith("Independently verify") for intent in beat.intents)
    assert len(memory.appended) == 1 and memory.appended[0].scope == "team"
    assert lander.landed == [uid("task-release")]
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.DONE  # type: ignore[union-attr]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None
    assert contract.status is DelegationContractStatus.DONE
    assert contract.accepted_run_id is not None and contract.accepted_at is not None
    team = ledger.teams.get(uid("team-release"))
    assert team is not None and team.status is TeamStatus.ARCHIVED
    contract_events = ledger.activity.by_subject("delegation_contract", uid("task-release"))
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload["passed"] is True
    assert "reviewer_id" not in contract_events[-1].payload  # no verifier principal involved
    assert not [
        run for run in ledger.runs.for_task(uid("task-release")) if run.principal_kind == "system"
    ]  # the lead's own acceptance IS the verdict — no system run row
    assert lead.role == "backend_engineer"


async def test_failed_parent_verification_returns_contract_to_integrating(
    ledger: Ledger,
) -> None:
    # Operator decision (2026-07-18): no verifier beat — the failing verdict is the lead's OWN
    # integrate beat (self-judged in-beat evaluation), which returns the contract to INTEGRATING.
    _seed_delegation(ledger)
    beat = _RecordingBeat(passed=False)
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None
    assert contract.status is DelegationContractStatus.INTEGRATING
    assert contract.accepted_run_id is not None and contract.accepted_at is not None
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert lander.landed == []
    queued = ledger.wakes.queued(employee_id="lead")
    assert len(queued) == 1
    assert queued[0].reason is WakeReason.CHILDREN_DONE
    contract_events = ledger.activity.by_subject("delegation_contract", uid("task-release"))
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload["passed"] is False
    assert "reviewer_id" not in contract_events[-1].payload  # no verifier principal involved


async def test_rejected_required_child_cannot_reach_acceptance_or_verification(
    ledger: Ledger,
) -> None:
    _seed_delegation(ledger, child_status=TaskStatus.REJECTED)
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.INTEGRATING
    assert contract.accepted_run_id is None
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert not any(intent.startswith("Independently verify") for intent in beat.intents)
    assert ledger.activity.by_subject("delegation_contract", uid("task-release")) == []


async def test_authority_denial_is_never_laundered_into_delegated_success(
    ledger: Ledger,
) -> None:
    """A profile denial refuses the beat BEFORE it runs — on a parent WITH children that must
    surface as a FAILED run + recovery, never as the 'success by delegating' branch (which would
    record SUCCEEDED and walk the denial into lead acceptance)."""
    _seed_delegation(ledger)
    ledger.teams.archive(uid("team-release"))  # revoked mid-flight → ExecutionProfileDenied
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    assert beat.rubrics == []  # the denied beat never reached the runner
    runs = ledger.runs.for_task(uid("task-release"))
    assert [run.status.value for run in runs] == ["failed"]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.accepted_run_id is None
    assert ledger.activity.by_subject("delegation_contract", uid("task-release")) == []
    assert ledger.recovery_actions.active_for_source(uid("task-release")) is not None


async def test_unmigrated_manager_is_blocked_before_dispatch(
    ledger: Ledger, caplog: pytest.LogCaptureFixture
) -> None:
    manager = ledger.employees.create(
        Employee(id=uid("legacy-manager"), name="Legacy Manager", role="manager")
    )
    ledger.tasks.submit(
        Task(
            id=uid("legacy-task"),
            intent="ambiguous manager work",
            status=TaskStatus.TODO,
            assignee_employee_id=manager.id,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-legacy"),
            employee_id=manager.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": uid("legacy-task")},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    with caplog.at_level(logging.WARNING, logger="chorus.heartbeat.scheduler"):
        report = await scheduler.tick(_NOW)
        await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    assert ledger.wakes.queued() == []
    assert ledger.tasks.get(uid("legacy-task")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source(uid("legacy-task"))
    assert recovery is not None and recovery.cause == "unmigrated_manager"
    assert recovery.owner_user_id == "operator"
    assert uid("legacy-manager") in caplog.text and "specialize-manager" in caplog.text


async def test_invalid_scoped_child_is_blocked_before_dispatch(ledger: Ledger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    parent = ledger.tasks.submit(
        Task(
            id=uid("scope-parent"),
            intent="ship the scoped work",
            status=TaskStatus.BLOCKED,
            files_to_touch=("src/parent.py",),
            assignee_employee_id="lead",
        )
    )
    worker = ledger.employees.create(Employee(id="scope-worker", name="Worker", role="engineer"))
    child = ledger.tasks.submit(
        Task(
            id=uid("scope-child"),
            parent_id=parent.id,
            intent="touch the wrong file",
            status=TaskStatus.TODO,
            assignee_employee_id=worker.id,
            files_to_touch=("src/other.py",),
        )
    )
    ledger.dependencies.add(parent.id, child.id)
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-scope-child"),
            employee_id=worker.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": child.id},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    report = await scheduler.tick(_NOW)
    await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    assert ledger.wakes.queued() == []
    blocked = ledger.tasks.get(child.id)
    assert blocked is not None and blocked.status is TaskStatus.BLOCKED
    recovery = ledger.recovery_actions.active_for_source(child.id)
    assert recovery is not None and recovery.cause == "invalid_file_scope"


async def test_invalid_scoped_delegation_blocks_the_contract_before_dispatch(ledger: Ledger) -> None:
    lead = ledger.employees.create(Employee(id="scope-lead", name="Lead", role="backend_engineer"))
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=2,
            allowed_professions=("backend_engineer",),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id=uid("scope-team"),
            name="Scope Team",
            lead_employee_id=lead.id,
            created_by="user-admin",
            status=TeamStatus.ACTIVE,
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("scope-team"),
            employee_id=lead.id,
            source_manager_id=lead.id,
            membership_role=TeamMembershipRole.LEAD,
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("scope-delegation"),
            intent="coordinate the release",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("scope-team"),
            assignee_employee_id=lead.id,
            files_to_touch=("/tmp/not-allowed",),
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("scope-delegation"),
            team_id=uid("scope-team"),
            lead_employee_id=lead.id,
            management_profile_version=1,
            max_depth=1,
            max_team_size=2,
            objective_rubric=_RUBRIC,
            status=DelegationContractStatus.INTEGRATING,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-scope-delegation"),
            employee_id=lead.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": uid("scope-delegation")},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    report = await scheduler.tick(_NOW)
    await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    task = ledger.tasks.get(uid("scope-delegation"))
    assert task is not None and task.status is TaskStatus.BLOCKED
    contract = ledger.delegation_contracts.get(uid("scope-delegation"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    recovery = ledger.recovery_actions.active_for_source(uid("scope-delegation"))
    assert recovery is not None and recovery.cause == "invalid_file_scope"


async def test_delegation_integrate_cap_accepts_completed_subtree(
    ledger: Ledger,
) -> None:
    # At the integrate cap, a delegation whose subtree produced REAL deliverables (>=1 done child)
    # AND passes its objective floor is ACCEPTED by the kernel on the manager's behalf — exactly what
    # the manager brief promises ("after a few iterations the kernel accepts for you"). It converges
    # to done so the goal can roll up, instead of stranding for a human even though the work is there.
    _seed_delegation(ledger)  # children DONE by default
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.DONE
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.DONE  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ARCHIVED  # type: ignore[union-attr]
    # accepted mechanically at the cap — no model rubric beat runs, but the subtree lands
    assert beat.rubrics == []
    assert lander.landed == [uid("task-release")]
    # real work converged, so no stranding recovery is opened
    assert ledger.recovery_actions.active_for_source(uid("task-release")) is None


async def test_delegation_integrate_cap_strands_when_nothing_converged(
    ledger: Ledger,
) -> None:
    # The honest guard: at the cap, a delegation whose subtree produced NO completed deliverable
    # (its only child was rejected) is NOT force-accepted — it strands for human review. The kernel
    # accepts real work, never fabricates a pass over failed work.
    _seed_delegation(ledger, child_status=TaskStatus.REJECTED)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source(uid("task-release"))
    assert recovery is not None
    assert recovery.cause == "integrate_iteration_exhausted"
    assert recovery.evidence["done_children"] == 0  # type: ignore[index]
    assert lander.landed == []


async def test_restart_closes_landed_delegation_exactly_once(
    ledger: Ledger,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_delegation(ledger)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    crashed_scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )
    land_passed = crashed_scheduler._land_passed

    async def crash_after_landing(*args: Any, **kwargs: Any) -> None:
        await land_passed(*args, **kwargs)
        raise RuntimeError("injected crash after delegation landing")

    monkeypatch.setattr(crashed_scheduler, "_land_passed", crash_after_landing)

    await crashed_scheduler.tick(_NOW)
    with pytest.raises(RuntimeError, match="injected crash"):
        await crashed_scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.VERIFYING
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.DONE  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert ledger.wakes.get(uid("wake-release")).status is WakeStatus.CLAIMED  # type: ignore[union-attr]

    restarted_scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )
    report = await restarted_scheduler.tick(_NOW)
    await restarted_scheduler.drain()

    assert report.recovered == 1
    assert lander.landed == [uid("task-release")]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.DONE
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ARCHIVED  # type: ignore[union-attr]
    assert ledger.wakes.get(uid("wake-release")).status is WakeStatus.DONE  # type: ignore[union-attr]
    contract_events = ledger.activity.by_subject("delegation_contract", uid("task-release"))
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload == {
        "passed": True,
        "recovered": True,
        "run_id": contract.accepted_run_id,
    }
