# Generated by AI (UnitTest MCP)
"""The scheduler consumes one complete task-aware execution profile."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

import pytest

from chorus.events import Event, EventKind
from chorus.governance import (
    ApprovalDecision,
    GovernanceError,
    GovernanceResolver,
    HumanAuthorization,
)
from chorus.heartbeat import Scheduler, Wake, WakeReason
from chorus.heartbeat._beat import BeatOutcome
from chorus.ledger import (
    ActivityVerb,
    ApprovalStatus,
    AuthenticationMethod,
    DelegationContract,
    DelegationContractStatus,
    DodStatus,
    ExecutionMode,
    Ledger,
    ManagementProfile,
    Task,
    TaskStatus,
    Team,
    TeamMember,
    TeamMembershipRole,
    TeamStatus,
    WakeStatus,
)
from chorus.ledger import (
    Artifact as LedgerArtifact,
)
from chorus.ledger import (
    ArtifactType as LedgerArtifactType,
)
from chorus.memory import SprintDelta
from chorus.outcomes import Artifact, ArtifactType, LanderRegistry, Verifier
from chorus.roles import RoleRegistry, default_roles
from chorus.testing import uid
from chorus.workforce import Employee, LedgerWorkforce

pytestmark = pytest.mark.integration

_NOW = datetime(2026, 6, 17, 12, tzinfo=UTC)
_RUBRIC = "integrate every release outcome and independently verify the assembled result"


def _authorization(label: str) -> HumanAuthorization:
    return HumanAuthorization(
        decision_id=uid(f"decision-{label}"),
        user_id="operator",
        method=AuthenticationMethod.STEP_UP,
        authenticated_at=_NOW,
        nonce=uid(f"nonce-{label}"),
        decided_at=_NOW,
        request_id=f"delegation-{label}",
        request_hash=f"sha256:delegation-{label}",
    )


class _RecordingBeat:
    def __init__(self, *, passed: bool = True, review_passed: bool | None = None) -> None:
        self.rubrics: list[str] = []
        self.passed = passed
        self.review_passed = review_passed
        self.intents: list[str] = []

    async def run_task(
        self,
        *,
        task_id: str,
        intent: str,
        verification: object = (),
        rubric: str = "",
        observer: object = None,
        run_id: str | None = None,
    ) -> BeatOutcome:
        self.rubrics.append(rubric)
        self.intents.append(intent)
        passed = (
            self.review_passed
            if intent.startswith("Independently verify") and self.review_passed is not None
            else self.passed
        )
        return BeatOutcome(
            passed=passed,
            outcome={},
            summary="release subtree integrated" if passed else "objective verification failed",
        )


class _RecordingMemory:
    def __init__(self) -> None:
        self.appended: list[SprintDelta] = []

    def append(self, delta: SprintDelta) -> None:
        self.appended.append(delta)


class _RecordingEvents:
    def __init__(self) -> None:
        self.events: list[Event] = []

    def emit(self, event: Event) -> None:
        self.events.append(event)

    def landed_for(self, task_id: str) -> list[Event]:
        return [
            event
            for event in self.events
            if event.kind is EventKind.OUTCOME_LANDED and event.task_id == task_id
        ]


class _SubtreeLander:
    outcome_kind = "subtree"

    def __init__(self) -> None:
        self.landed: list[str] = []

    async def land(self, task: Any, result: Any) -> Artifact:
        self.landed.append(task.id)
        return Artifact(
            task_id=task.id,
            type=ArtifactType.ARTIFACT,
            resource_ref={"kind": "subtree"},
        )


def _seed_delegation(ledger: Ledger, *, child_status: TaskStatus = TaskStatus.DONE) -> Employee:
    lead = ledger.employees.create(Employee(id="lead", name="Lead", role="backend_engineer"))
    worker = ledger.employees.create(
        Employee(id="worker", name="Worker", role="backend_engineer", reports_to=lead.id)
    )
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=2,
            allowed_professions=("backend_engineer",),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id=uid("team-release"),
            name="Release",
            lead_employee_id=lead.id,
            created_by="user-admin",
            status=TeamStatus.ACTIVE,
        )
    )
    for employee_id, membership_role in (
        (lead.id, TeamMembershipRole.LEAD),
        (worker.id, TeamMembershipRole.MEMBER),
    ):
        ledger.team_members.add(
            TeamMember(
                team_id=uid("team-release"),
                employee_id=employee_id,
                source_manager_id=lead.id,
                membership_role=membership_role,
            )
        )
    ledger.tasks.submit(
        Task(
            id=uid("task-release"),
            intent="coordinate the release",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("team-release"),
            assignee_employee_id=lead.id,
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("task-child"),
            parent_id=uid("task-release"),
            intent="implement the release endpoint",
            status=child_status,
            assignee_employee_id=worker.id,
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("task-release"),
            team_id=uid("team-release"),
            lead_employee_id=lead.id,
            management_profile_version=1,
            max_depth=1,
            max_team_size=2,
            objective_rubric=_RUBRIC,
            status=DelegationContractStatus.INTEGRATING,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-release"),
            employee_id=lead.id,
            reason=WakeReason.CHILDREN_DONE,
            payload={"task_id": uid("task-release")},
        )
    )
    return lead


def _seed_delivery_parent(ledger: Ledger, *, child_status: TaskStatus = TaskStatus.DONE) -> Employee:
    lead = ledger.employees.create(Employee(id="lead", name="Lead", role="backend_engineer"))
    worker = ledger.employees.create(
        Employee(id="worker", name="Worker", role="backend_engineer", reports_to=lead.id)
    )
    ledger.tasks.submit(
        Task(
            id=uid("task-release"),
            intent="coordinate the release",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELIVERY,
            assignee_employee_id=lead.id,
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("task-child"),
            parent_id=uid("task-release"),
            intent="implement the release endpoint",
            status=child_status,
            assignee_employee_id=worker.id,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-release"),
            employee_id=lead.id,
            reason=WakeReason.CHILDREN_DONE,
            payload={"task_id": uid("task-release")},
        )
    )
    return lead


async def test_delegation_profile_drives_scheduler_contract(ledger: Ledger) -> None:
    lead = _seed_delegation(ledger)
    beat = _RecordingBeat()
    memory = _RecordingMemory()
    lander = _SubtreeLander()
    events = _RecordingEvents()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=memory,
        event_bus=events,
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    verifier = ledger.dod.verifier_for_task(uid("task-release"))
    assert verifier is not None
    assert (verifier.rubric(), verifier.artifact_class) == (_RUBRIC, "subtree")
    # Operator decision (2026-07-18): employees verify their own work — the lead's single integrate
    # beat is the only run; no "Independently verify" system-verifier beat follows it.
    assert beat.rubrics == [_RUBRIC]
    assert not any(intent.startswith("Independently verify") for intent in beat.intents)
    assert len(memory.appended) == 1 and memory.appended[0].scope == "team"
    assert lander.landed == [uid("task-release")]
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.DONE  # type: ignore[union-attr]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None
    assert contract.status is DelegationContractStatus.DONE
    assert contract.accepted_run_id is not None and contract.accepted_at is not None
    team = ledger.teams.get(uid("team-release"))
    assert team is not None and team.status is TeamStatus.ARCHIVED
    contract_events = ledger.activity.by_subject("delegation_contract", uid("task-release"))
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload["passed"] is True
    assert "reviewer_id" not in contract_events[-1].payload  # no verifier principal involved
    assert not [
        run for run in ledger.runs.for_task(uid("task-release")) if run.principal_kind == "system"
    ]  # the lead's own acceptance IS the verdict — no system run row
    assert lead.role == "backend_engineer"
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is True and dod.integration_note is None
    assert events.landed_for(uid("task-release"))[-1].payload["integration_ok"] is True
    assert events.landed_for(uid("task-release"))[-1].payload["integration_note"] is None


async def test_failed_parent_verification_returns_contract_to_integrating(
    ledger: Ledger,
) -> None:
    # Operator decision (2026-07-18): no verifier beat — the failing verdict is the lead's OWN
    # integrate beat (self-judged in-beat evaluation), which returns the contract to INTEGRATING.
    _seed_delegation(ledger)
    beat = _RecordingBeat(passed=False)
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None
    assert contract.status is DelegationContractStatus.INTEGRATING
    assert contract.accepted_run_id is not None and contract.accepted_at is not None
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert lander.landed == []
    queued = ledger.wakes.queued(employee_id="lead")
    assert len(queued) == 1
    assert queued[0].reason is WakeReason.CHILDREN_DONE
    contract_events = ledger.activity.by_subject("delegation_contract", uid("task-release"))
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload["passed"] is False
    assert "reviewer_id" not in contract_events[-1].payload  # no verifier principal involved
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note == "delegation integration failed: lead integration verdict did not pass"


async def test_rejected_required_child_cannot_reach_acceptance_or_verification(
    ledger: Ledger,
) -> None:
    _seed_delegation(ledger, child_status=TaskStatus.REJECTED)
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.INTEGRATING
    assert contract.accepted_run_id is None
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert not any(intent.startswith("Independently verify") for intent in beat.intents)
    assert ledger.activity.by_subject("delegation_contract", uid("task-release")) == []


async def test_authority_denial_is_never_laundered_into_delegated_success(
    ledger: Ledger,
) -> None:
    """A profile denial refuses the beat BEFORE it runs — on a parent WITH children that must
    surface as a FAILED run + recovery, never as the 'success by delegating' branch (which would
    record SUCCEEDED and walk the denial into lead acceptance)."""
    _seed_delegation(ledger)
    ledger.teams.archive(uid("team-release"))  # revoked mid-flight → ExecutionProfileDenied
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    assert beat.rubrics == []  # the denied beat never reached the runner
    runs = ledger.runs.for_task(uid("task-release"))
    assert [run.status.value for run in runs] == ["failed"]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.accepted_run_id is None
    assert ledger.activity.by_subject("delegation_contract", uid("task-release")) == []
    assert ledger.recovery_actions.active_for_source(uid("task-release")) is not None


async def test_integrate_cap_wins_over_profile_denial(
    ledger: Ledger,
) -> None:
    _seed_delegation(ledger)
    ledger.teams.archive(uid("team-release"))  # revoked mid-flight, but cap exhaustion is deterministic
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    assert beat.rubrics == []
    runs = ledger.runs.for_task(uid("task-release"))
    assert [run.status.value for run in runs] == ["failed"]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    assert contract.accepted_run_id is None
    task = ledger.tasks.get(uid("task-release"))
    assert task is not None and task.status is TaskStatus.BLOCKED
    assert task.checkout_run_id is None
    assert task.execution_run_id is None
    recovery = ledger.recovery_actions.active_for_source(uid("task-release"))
    assert recovery is not None and recovery.cause == "integrate_iteration_exhausted"
    assert ledger.wakes.get(uid("wake-release")).status is WakeStatus.DONE  # type: ignore[union-attr]
    assert ledger.activity.by_subject("delegation_contract", uid("task-release")) == []


async def test_unmigrated_manager_is_blocked_before_dispatch(
    ledger: Ledger, caplog: pytest.LogCaptureFixture
) -> None:
    manager = ledger.employees.create(
        Employee(id=uid("legacy-manager"), name="Legacy Manager", role="manager")
    )
    ledger.tasks.submit(
        Task(
            id=uid("legacy-task"),
            intent="ambiguous manager work",
            status=TaskStatus.TODO,
            assignee_employee_id=manager.id,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-legacy"),
            employee_id=manager.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": uid("legacy-task")},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    with caplog.at_level(logging.WARNING, logger="chorus.heartbeat.scheduler"):
        report = await scheduler.tick(_NOW)
        await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    assert ledger.wakes.queued() == []
    assert ledger.tasks.get(uid("legacy-task")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source(uid("legacy-task"))
    assert recovery is not None and recovery.cause == "unmigrated_manager"
    assert recovery.owner_user_id == "operator"
    assert uid("legacy-manager") in caplog.text and "specialize-manager" in caplog.text


async def test_invalid_scoped_child_is_blocked_before_dispatch(ledger: Ledger) -> None:
    ledger.employees.create(Employee(id="lead", name="Lead", role="engineer"))
    parent = ledger.tasks.submit(
        Task(
            id=uid("scope-parent"),
            intent="ship the scoped work",
            status=TaskStatus.BLOCKED,
            files_to_touch=("src/parent.py",),
            assignee_employee_id="lead",
        )
    )
    worker = ledger.employees.create(Employee(id="scope-worker", name="Worker", role="engineer"))
    child = ledger.tasks.submit(
        Task(
            id=uid("scope-child"),
            parent_id=parent.id,
            intent="touch the wrong file",
            status=TaskStatus.TODO,
            assignee_employee_id=worker.id,
            files_to_touch=("src/other.py",),
        )
    )
    ledger.dependencies.add(parent.id, child.id)
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-scope-child"),
            employee_id=worker.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": child.id},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    report = await scheduler.tick(_NOW)
    await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    assert ledger.wakes.queued() == []
    blocked = ledger.tasks.get(child.id)
    assert blocked is not None and blocked.status is TaskStatus.BLOCKED
    recovery = ledger.recovery_actions.active_for_source(child.id)
    assert recovery is not None and recovery.cause == "invalid_file_scope"
    assert recovery.next_action is not None
    assert "cancel" in recovery.next_action and "recreate" in recovery.next_action
    assert "repair files_to_touch" not in recovery.next_action


async def test_invalid_scoped_delegation_blocks_the_contract_before_dispatch(ledger: Ledger) -> None:
    lead = ledger.employees.create(Employee(id="scope-lead", name="Lead", role="backend_engineer"))
    ledger.management_profiles.upsert(
        ManagementProfile(
            employee_id=lead.id,
            granted_by_user_id="user-admin",
            active=True,
            can_lead=True,
            max_delegation_depth=1,
            max_team_size=2,
            allowed_professions=("backend_engineer",),
            version=1,
        )
    )
    ledger.teams.create(
        Team(
            id=uid("scope-team"),
            name="Scope Team",
            lead_employee_id=lead.id,
            created_by="user-admin",
            status=TeamStatus.ACTIVE,
        )
    )
    ledger.team_members.add(
        TeamMember(
            team_id=uid("scope-team"),
            employee_id=lead.id,
            source_manager_id=lead.id,
            membership_role=TeamMembershipRole.LEAD,
        )
    )
    ledger.tasks.submit(
        Task(
            id=uid("scope-delegation"),
            intent="coordinate the release",
            status=TaskStatus.TODO,
            execution_mode=ExecutionMode.DELEGATION,
            team_id=uid("scope-team"),
            assignee_employee_id=lead.id,
            files_to_touch=("/tmp/not-allowed",),
        )
    )
    ledger.delegation_contracts.create(
        DelegationContract(
            task_id=uid("scope-delegation"),
            team_id=uid("scope-team"),
            lead_employee_id=lead.id,
            management_profile_version=1,
            max_depth=1,
            max_team_size=2,
            objective_rubric=_RUBRIC,
            status=DelegationContractStatus.INTEGRATING,
        )
    )
    ledger.wakes.enqueue(
        Wake(
            id=uid("wake-scope-delegation"),
            employee_id=lead.id,
            reason=WakeReason.TASK_ASSIGNED,
            payload={"task_id": uid("scope-delegation")},
        )
    )
    beat = _RecordingBeat()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    report = await scheduler.tick(_NOW)
    await scheduler.drain()

    assert report.beats_started == 0
    assert beat.rubrics == []
    task = ledger.tasks.get(uid("scope-delegation"))
    assert task is not None and task.status is TaskStatus.BLOCKED
    contract = ledger.delegation_contracts.get(uid("scope-delegation"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    recovery = ledger.recovery_actions.active_for_source(uid("scope-delegation"))
    assert recovery is not None and recovery.cause == "invalid_file_scope"
    assert recovery.next_action is not None
    assert "cancel" in recovery.next_action and "recreate" in recovery.next_action
    assert "repair files_to_touch" not in recovery.next_action


async def test_delegation_integrate_cap_blocks_completed_subtree_for_review(
    ledger: Ledger,
) -> None:
    _seed_delegation(ledger)  # children DONE by default
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    assert contract.accepted_run_id is None
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert beat.rubrics == []
    assert lander.landed == []
    recovery = ledger.recovery_actions.active_for_source(uid("task-release"))
    assert recovery is not None and recovery.cause == "integrate_iteration_exhausted"
    done_children = recovery.evidence.get("done_children")
    assert isinstance(done_children, int) and done_children > 0
    assert not ledger.activity.by_subject("delegation_contract", uid("task-release"))
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note is not None
    assert "stranded for human review without fabricating acceptance" in dod.integration_note
    assert ledger.tasks.get(uid("task-release")).status is not TaskStatus.DONE  # type: ignore[union-attr]


async def test_delegation_integrate_cap_strands_when_nothing_converged(
    ledger: Ledger,
) -> None:
    # At the cap, a delegation whose subtree produced no completed deliverable (its only child was
    # rejected) strands for human review. Cap exhaustion never fabricates a pass over failed work.
    _seed_delegation(ledger, child_status=TaskStatus.REJECTED)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source(uid("task-release"))
    assert recovery is not None
    assert recovery.cause == "integrate_iteration_exhausted"
    done_children = recovery.evidence.get("done_children")
    assert done_children == 0
    assert lander.landed == []
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note is not None
    assert "stranded for human review without fabricating acceptance" in dod.integration_note
    assert ledger.tasks.get(uid("task-release")).status is not TaskStatus.DONE  # type: ignore[union-attr]


async def test_delivery_integrate_cap_blocks_completed_subtree_for_review(
    ledger: Ledger,
) -> None:
    _seed_delivery_parent(ledger)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source(uid("task-release"))
    assert recovery is not None and recovery.cause == "integrate_iteration_exhausted"
    done_children = recovery.evidence.get("done_children")
    assert isinstance(done_children, int) and done_children > 0
    runs = ledger.runs.for_task(uid("task-release"))
    assert runs[-1].status.value == "failed"
    assert lander.landed == []
    assert beat.rubrics == []


async def test_restart_closes_landed_delegation_exactly_once(
    ledger: Ledger,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_delegation(ledger)
    beat = _RecordingBeat()
    lander = _SubtreeLander()
    crashed_scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )
    land_passed = crashed_scheduler._land_passed

    async def crash_after_landing(*args: Any, **kwargs: Any) -> None:
        await land_passed(*args, **kwargs)
        raise RuntimeError("injected crash after delegation landing")

    monkeypatch.setattr(crashed_scheduler, "_land_passed", crash_after_landing)

    await crashed_scheduler.tick(_NOW)
    with pytest.raises(RuntimeError, match="injected crash"):
        await crashed_scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.VERIFYING
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.DONE  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    assert ledger.wakes.get(uid("wake-release")).status is WakeStatus.CLAIMED  # type: ignore[union-attr]

    restarted_scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=beat,
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([lander]),
        max_concurrent_runs=1,
    )
    report = await restarted_scheduler.tick(_NOW)
    await restarted_scheduler.drain()

    assert report.recovered == 1
    assert lander.landed == [uid("task-release")]
    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.DONE
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ARCHIVED  # type: ignore[union-attr]
    assert ledger.wakes.get(uid("wake-release")).status is WakeStatus.DONE  # type: ignore[union-attr]
    contract_events = ledger.activity.by_subject("delegation_contract", uid("task-release"))
    assert [event.verb for event in contract_events] == [
        ActivityVerb.LEAD_ACCEPTED,
        ActivityVerb.PARENT_VERIFIED,
    ]
    assert contract_events[-1].payload == {
        "passed": True,
        "recovered": True,
        "run_id": contract.accepted_run_id,
    }


@pytest.mark.parametrize("malformed", ["false", 0])
async def test_malformed_child_pr_merge_receipt_fails_closed(
    ledger: Ledger,
    malformed: object,
) -> None:
    _seed_delegation(ledger)
    ledger.artifacts.create(
        LedgerArtifact(
            id=uid("malformed-merge"),
            task_id=uid("task-child"),
            type=LedgerArtifactType.PR,
            is_primary=True,
            resource_ref={"merged": malformed},
        )
    )
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note is not None
    assert "malformed merge evidence" in dod.integration_note
    assert "must be a boolean" in dod.integration_note
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]


@pytest.mark.parametrize("resource_ref", [None, {}])
async def test_missing_child_pr_merge_receipt_fails_closed(
    ledger: Ledger,
    resource_ref: dict[str, object] | None,
) -> None:
    _seed_delegation(ledger)
    ledger.artifacts.create(
        LedgerArtifact(
            id=uid("missing-merge"),
            task_id=uid("task-child"),
            type=LedgerArtifactType.PR,
            is_primary=True,
            resource_ref=resource_ref,
        )
    )
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note is not None
    assert "requires an explicit resource_ref.merged boolean" in dod.integration_note


async def test_unmerged_child_pr_fails_closed_without_fabricating_acceptance(ledger: Ledger) -> None:
    _seed_delegation(ledger)
    ledger.artifacts.create(
        LedgerArtifact(
            id=uid("unmerged"),
            task_id=uid("task-child"),
            type=LedgerArtifactType.PR,
            is_primary=True,
            resource_ref={"merged": False},
        )
    )
    events = _RecordingEvents()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        event_bus=events,
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note is not None
    assert "resource_ref.merged=false" in dod.integration_note
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    landed = events.landed_for(uid("task-release"))
    assert landed[-1].payload["integration_ok"] is False
    assert landed[-1].payload["phase"] != "terminal_pass"


@pytest.mark.parametrize(
    (
        "decision",
        "task_status",
        "contract_status",
        "dod_status",
        "team_status",
        "phase",
        "passed",
    ),
    [
        (
            ApprovalDecision.APPROVE,
            TaskStatus.DONE,
            DelegationContractStatus.DONE,
            DodStatus.PASSED,
            TeamStatus.ARCHIVED,
            "terminal_pass",
            True,
        ),
        (
            ApprovalDecision.DENY,
            TaskStatus.BLOCKED,
            DelegationContractStatus.BLOCKED,
            DodStatus.FAILED,
            TeamStatus.ACTIVE,
            "needs_rework",
            False,
        ),
        (
            ApprovalDecision.REQUEST_REVISION,
            TaskStatus.TODO,
            DelegationContractStatus.INTEGRATING,
            DodStatus.FAILED,
            TeamStatus.ACTIVE,
            "needs_rework",
            False,
        ),
    ],
)
async def test_delegated_human_approval_resolves_contract_only_on_terminal_decision(
    ledger: Ledger,
    decision: ApprovalDecision,
    task_status: TaskStatus,
    contract_status: DelegationContractStatus,
    dod_status: DodStatus,
    team_status: TeamStatus,
    phase: str,
    passed: bool,
) -> None:
    _seed_delegation(ledger)
    ledger.dod.create(uid("task-release"), Verifier.human_approval())
    events = _RecordingEvents()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        event_bus=events,
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    pending = ledger.approvals.pending()
    assert len(pending) == 1
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert (
        ledger.delegation_contracts.get(uid("task-release")).status
        is DelegationContractStatus.VERIFYING
    )  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    before = ledger.dod.get_for_task(uid("task-release"))
    assert before is not None and before.status is DodStatus.PENDING
    assert before.integration_ok is True
    assert events.landed_for(uid("task-release")) == []

    resolver = GovernanceResolver(ledger, event_sink=events)
    with pytest.raises(GovernanceError, match="requires authenticated"):
        resolver.resolve(
            pending[0].id,
            decision=decision,
            decided_by_user_id="operator",
            now=_NOW,
        )
    assert events.landed_for(uid("task-release")) == []

    resolver.resolve_authenticated(
        pending[0].id,
        decision=decision,
        authorization=_authorization(decision.value),
    )

    assert ledger.tasks.get(uid("task-release")).status is task_status  # type: ignore[union-attr]
    assert ledger.delegation_contracts.get(uid("task-release")).status is contract_status  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is team_status  # type: ignore[union-attr]
    after = ledger.dod.get_for_task(uid("task-release"))
    assert after is not None and after.status is dod_status
    assert after.integration_ok is True and after.integration_note is None
    landed = events.landed_for(uid("task-release"))
    assert len(landed) == 1
    assert landed[0].payload["phase"] == phase
    assert landed[0].payload["passed"] is passed


async def test_human_acceptance_resolution_between_gate_and_scheduler_emit_is_exactly_once(
    ledger: Ledger,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _seed_delegation(ledger)
    ledger.dod.create(uid("task-release"), Verifier.human_approval())
    events = _RecordingEvents()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        event_bus=events,
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )
    scheduler_emit = scheduler._emit_outcome_landed

    def decide_then_project(
        *,
        task: Task,
        result: BeatOutcome,
        run_id: str,
        employee: Employee,
        now: datetime,
        files_touched: tuple[str, ...],
        todo_digest: str,
        this_beat_landing: object = None,
    ) -> None:
        (approval,) = ledger.approvals.pending()
        GovernanceResolver(ledger, event_sink=events).resolve_authenticated(
            approval.id,
            decision=ApprovalDecision.APPROVE,
            authorization=_authorization("interleaved-approve"),
        )
        scheduler_emit(
            task=task,
            result=result,
            run_id=run_id,
            employee=employee,
            now=now,
            files_touched=files_touched,
            todo_digest=todo_digest,
            this_beat_landing=this_beat_landing,
        )

    monkeypatch.setattr(scheduler, "_emit_outcome_landed", decide_then_project)

    await scheduler.tick(_NOW)
    await scheduler.drain()

    (approval,) = ledger.approvals.for_subject(uid("task-release"))
    assert len(events.landed_for(uid("task-release"))) == 1
    durable = [
        row
        for row in ledger.activity.by_subject("approval", approval.id)
        if row.verb is ActivityVerb.OUTCOME_LANDED
    ]
    assert len(durable) == 1


async def test_delegated_human_approval_hold_keeps_contract_and_team_open(ledger: Ledger) -> None:
    _seed_delegation(ledger)
    ledger.dod.create(uid("task-release"), Verifier.human_approval())
    events = _RecordingEvents()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        event_bus=events,
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )
    await scheduler.tick(_NOW)
    await scheduler.drain()
    (approval,) = ledger.approvals.pending()

    GovernanceResolver(ledger, event_sink=events).hold_authenticated(
        approval.id, authorization=_authorization("hold")
    )

    assert ledger.approvals.get(approval.id).status is ApprovalStatus.PENDING  # type: ignore[union-attr]
    assert (
        ledger.delegation_contracts.get(uid("task-release")).status
        is DelegationContractStatus.VERIFYING
    )  # type: ignore[union-attr]
    assert ledger.teams.get(uid("team-release")).status is TeamStatus.ACTIVE  # type: ignore[union-attr]
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.status is DodStatus.PENDING and dod.integration_ok is True
    assert events.landed_for(uid("task-release")) == []


@pytest.mark.parametrize(
    ("resource_ref", "expected_note"),
    [
        ({"merged": False}, "resource_ref.merged=false"),
        ({"merged": "false"}, "malformed merge evidence"),
        ({"merged": 0}, "malformed merge evidence"),
        (None, "requires an explicit resource_ref.merged boolean"),
        ({}, "requires an explicit resource_ref.merged boolean"),
    ],
)
async def test_delegation_integrate_cap_rejects_failed_or_malformed_merge_evidence(
    ledger: Ledger,
    resource_ref: dict[str, object] | None,
    expected_note: str,
) -> None:
    _seed_delegation(ledger)
    ledger.artifacts.create(
        LedgerArtifact(
            id=uid("cap-merge"),
            task_id=uid("task-child"),
            type=LedgerArtifactType.PR,
            is_primary=True,
            resource_ref=resource_ref,
        )
    )
    events = _RecordingEvents()
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        event_bus=events,
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
        max_integrate_iterations=0,
    )

    await scheduler.tick(_NOW)
    await scheduler.drain()

    contract = ledger.delegation_contracts.get(uid("task-release"))
    assert contract is not None and contract.status is DelegationContractStatus.BLOCKED
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert ledger.tasks.get(uid("task-release")).status is not TaskStatus.DONE  # type: ignore[union-attr]
    recovery = ledger.recovery_actions.active_for_source(uid("task-release"))
    assert recovery is not None and recovery.cause == "integrate_iteration_exhausted"
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.integration_ok is False
    assert dod.integration_note is not None and expected_note in dod.integration_note
    assert "force-accepted" not in dod.integration_note
    landed = events.landed_for(uid("task-release"))
    assert len(landed) == 1
    assert landed[0].payload["phase"] == "stranded"
    assert landed[0].payload["passed"] is not True
    assert landed[0].payload["integration_ok"] is False
    assert landed[0].payload["integration_note"] == dod.integration_note


async def test_delegated_human_approval_resolution_rolls_back_and_survives_restart(
    pg_database: str,
) -> None:
    company_id = uid("delegated-human-company")
    ledger = Ledger.open(pg_database, company_id=company_id)
    _seed_delegation(ledger)
    ledger.dod.create(uid("task-release"), Verifier.human_approval())
    scheduler = Scheduler(
        ledger=ledger,
        workforce=LedgerWorkforce(ledger.employees),
        beat_runner=_RecordingBeat(),
        roles=RoleRegistry.from_plugins(default_roles()),
        memory_writer=_RecordingMemory(),
        landers=LanderRegistry.from_landers([_SubtreeLander()]),
        max_concurrent_runs=1,
    )
    await scheduler.tick(_NOW)
    await scheduler.drain()
    (approval,) = ledger.approvals.pending()
    authorization = _authorization("restart-approve")

    archive = ledger.teams.archive

    def fail_archive(team_id: str) -> Team:
        raise RuntimeError(f"injected archive failure for {team_id}")

    ledger.teams.archive = fail_archive  # type: ignore[method-assign]
    with pytest.raises(RuntimeError, match="injected archive failure"):
        GovernanceResolver(ledger).resolve_authenticated(
            approval.id,
            decision=ApprovalDecision.APPROVE,
            authorization=authorization,
        )
    ledger.teams.archive = archive  # type: ignore[method-assign]

    assert ledger.approvals.get(approval.id).status is ApprovalStatus.PENDING  # type: ignore[union-attr]
    assert GovernanceResolver(ledger).get_authorization_proof(approval.id) is None
    assert ledger.tasks.get(uid("task-release")).status is TaskStatus.BLOCKED  # type: ignore[union-attr]
    assert (
        ledger.delegation_contracts.get(uid("task-release")).status
        is DelegationContractStatus.VERIFYING
    )  # type: ignore[union-attr]
    dod = ledger.dod.get_for_task(uid("task-release"))
    assert dod is not None and dod.status is DodStatus.PENDING and dod.integration_ok is True
    ledger.close()

    restarted = Ledger.open(pg_database, company_id=company_id)
    restarted_resolver = GovernanceResolver(restarted)
    outcome = restarted_resolver.resolve_authenticated(
        approval.id,
        decision=ApprovalDecision.APPROVE,
        authorization=authorization,
    )
    assert restarted.tasks.get(uid("task-release")).status is TaskStatus.DONE  # type: ignore[union-attr]
    assert (
        restarted.delegation_contracts.get(uid("task-release")).status
        is DelegationContractStatus.DONE
    )  # type: ignore[union-attr]
    assert restarted.teams.get(uid("team-release")).status is TeamStatus.ARCHIVED  # type: ignore[union-attr]
    persisted = restarted.dod.get_for_task(uid("task-release"))
    assert persisted is not None and persisted.status is DodStatus.PASSED
    assert persisted.integration_ok is True and persisted.integration_note is None
    assert outcome.landed is not None and outcome.landed.phase.value == "terminal_pass"
    replayed = restarted_resolver.get_landed_outcome(approval.id)
    assert replayed == outcome.landed
    with pytest.raises(GovernanceError, match="already"):
        restarted_resolver.resolve_authenticated(
            approval.id,
            decision=ApprovalDecision.APPROVE,
            authorization=_authorization("duplicate-after-restart"),
        )
    durable = [
        row
        for row in restarted.activity.by_subject("approval", approval.id)
        if row.verb is ActivityVerb.OUTCOME_LANDED
    ]
    assert len(durable) == 1
    restarted.close()

    replay_ledger = Ledger.open(pg_database, company_id=company_id)
    try:
        assert GovernanceResolver(replay_ledger).get_landed_outcome(approval.id) == outcome.landed
    finally:
        replay_ledger.close()
