CREATE TABLE credential_registration (company_id uuid NOT NULL DEFAULT (NULLIF(current_setting('app.company_id', true), ''))::uuid, credential text NOT NULL, source_name text NOT NULL, owner text NOT NULL, audience text NOT NULL, purpose text NOT NULL, mode text NOT NULL, delivery text NOT NULL, environment_key text, allowed_host text, injection_header text NOT NULL, injection_scheme text NOT NULL, allowed_methods jsonb NOT NULL, allowed_paths jsonb NOT NULL, requested_at timestamptz NOT NULL, PRIMARY KEY (company_id, credential));
CREATE TABLE credential_ask (company_id uuid NOT NULL DEFAULT (NULLIF(current_setting('app.company_id', true), ''))::uuid, id text NOT NULL, credential text NOT NULL, audience text NOT NULL, purpose text NOT NULL, requested_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, status text NOT NULL, grant_id text, PRIMARY KEY (company_id, id));
CREATE TABLE credential_grant (company_id uuid NOT NULL DEFAULT (NULLIF(current_setting('app.company_id', true), ''))::uuid, id text NOT NULL, credential text NOT NULL, audience text NOT NULL, status text NOT NULL, mode text NOT NULL, purpose text NOT NULL, granted_at timestamptz NOT NULL, expires_at timestamptz, PRIMARY KEY (company_id, id));
CREATE TABLE credential_lease (company_id uuid NOT NULL DEFAULT (NULLIF(current_setting('app.company_id', true), ''))::uuid, handle text NOT NULL, grant_id text NOT NULL, session text NOT NULL, issued_at timestamptz NOT NULL, PRIMARY KEY (company_id, handle));
CREATE TABLE credential_use (company_id uuid NOT NULL DEFAULT (NULLIF(current_setting('app.company_id', true), ''))::uuid, grant_id text NOT NULL, session text NOT NULL, used_at timestamptz NOT NULL, PRIMARY KEY (company_id, grant_id, session));
ALTER TABLE credential_registration ENABLE ROW LEVEL SECURITY;
ALTER TABLE credential_registration FORCE ROW LEVEL SECURITY;
ALTER TABLE credential_ask ENABLE ROW LEVEL SECURITY;
ALTER TABLE credential_ask FORCE ROW LEVEL SECURITY;
ALTER TABLE credential_grant ENABLE ROW LEVEL SECURITY;
ALTER TABLE credential_grant FORCE ROW LEVEL SECURITY;
ALTER TABLE credential_lease ENABLE ROW LEVEL SECURITY;
ALTER TABLE credential_lease FORCE ROW LEVEL SECURITY;
ALTER TABLE credential_use ENABLE ROW LEVEL SECURITY;
ALTER TABLE credential_use FORCE ROW LEVEL SECURITY;
CREATE POLICY credential_registration_company ON credential_registration USING (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid)) WITH CHECK (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid));
CREATE POLICY credential_ask_company ON credential_ask USING (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid)) WITH CHECK (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid));
CREATE POLICY credential_grant_company ON credential_grant USING (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid)) WITH CHECK (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid));
CREATE POLICY credential_lease_company ON credential_lease USING (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid)) WITH CHECK (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid));
CREATE POLICY credential_use_company ON credential_use USING (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid)) WITH CHECK (company_id = (SELECT (NULLIF(current_setting('app.company_id', true), ''))::uuid));
